### PR TITLE
Use a fork of pgzero that pulls a newer version of pygame

### PR DESCRIPTION
**Pull request by carlosperate**
Also re-enable Python 3.8 support.

### CODE REVIEW

**Comment by ntoll** [comment]
Can we also try Python 3.9 support..?

**Comment by carlosperate** [comment]
Sure, I'll push an update now

**Comment by carlosperate** [comment]
Done 3.9 in a different branch to not overwrite the results from this changes:
- https://github.com/mu-editor/mu/tree/py39
- https://github.com/mu-editor/mu/actions/runs/531682254

**Comment by carlosperate** [comment]
Arm Debian is not happy, running the tests crashes it. Probably something pygame related.

**Comment by ntoll** [comment]
Hmmm.... so ARM as in RaspberryPi..?

**Comment by carlosperate** [comment]
It's actually crashed in one, but the other has run the tests and had some test failures, we'll have to see what they are.

> Hmmm.... so ARM as in RaspberryPi..?

Kind of, it is emulating Arm with Qemu and then running Debian for Arm on that.
It is meant to be close to the Raspberry Pi for testing, but it won't be a perfect replication.
I actually have a better version that can run Raspbian on Qemu, but haven't had a chance to add to Mu yet.

**Comment by carlosperate** [comment]
Failure:
- https://github.com/mu-editor/mu/pull/1269/checks?check_run_id=1816991234

```
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
Using --random-order-bucket=module
Using --random-order-seed=465073

rootdir: /github/workspace, configfile: pytest.ini
plugins: cov-2.11.1, random-order-1.0.4
collected 1008 items

tests/modes/test_microbit.py ........................................... [  4%]
.........                                                                [  5%]
tests/virtual_environment/test_virtual_environment.py .................. [  6%]
                                                                         [  6%]
tests/modes/test_web.py ....................                             [  8%]
tests/debugger/test_client.py .......................................... [ 13%]
.....                                                                    [ 13%]
tests/modes/test_esp.py ........................                         [ 15%]
tests/modes/test_pico.py .                                               [ 16%]
tests/debugger/test_utils.py ......                                      [ 16%]
tests/modes/test_python3.py ...........................                  [ 19%]
tests/test_settings.py .........s.............s...........               [ 22%]
tests/interface/test_themes.py ....                                      [ 23%]
tests/interface/test_editor.py ......................................... [ 27%]
.......                                                                  [ 27%]
tests/modes/test_pyboard.py .........                                    [ 28%]
tests/test_logic.py ..............................s..................... [ 34%]
......................................................s................. [ 41%]
.............................F.................................          [ 47%]
tests/interface/test_dialogs.py ....s..s...sss..s......sss.s.s.ss        [ 50%]
tests/debugger/test_runner.py .......................................... [ 54%]
.........                                                                [ 55%]
tests/modes/test_lego.py .                                               [ 55%]
tests/modes/test_circuitpython.py ...........                            [ 56%]
tests/interface/test_main.py ........................................... [ 61%]
........................................................                 [ 66%]
tests/modes/test_base.py ...s........................................... [ 71%]
...............                                                          [ 72%]
tests/virtual_environment/test_pip.py ..................                 [ 74%]
tests/modes/test_debug.py ........................................       [ 78%]
tests/test_resources.py ......                                           [ 79%]
tests/interface/test_widgets.py .........                                [ 80%]
tests/test_app.py .........                                              [ 81%]
tests/modes/test_pygamezero.py ..................                        [ 82%]
tests/interface/test_panes.py .......................................... [ 87%]
......................................s................................. [ 94%]
.....................................................                    [ 99%]
tests/virtual_environment/test_process.py ......                         [100%]

=================================== FAILURES ===================================
_________________ test_editor_restore_session_existing_runtime _________________

    def test_editor_restore_session_existing_runtime():
        """
        A correctly specified session is restored properly.
        """
        mode, theme = "python", "night"
        file_contents = ["", ""]
        ed = mocked_editor(mode)
        with mock.patch("os.path.isfile", return_value=True):
            with mock.patch.object(venv, "relocate") as venv_relocate:
                with generate_session(
                    theme,
                    mode,
                    file_contents,
                    microbit_runtime="/foo",
                    zoom_level=5,
                    venv_path="foo",
                ):
>                   ed.restore_session()

tests/test_logic.py:878: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mu/logic.py:920: in restore_session
    venv.ensure()
mu/virtual_environment.py:361: in ensure
    self.create()
mu/virtual_environment.py:418: in create
    self.install_baseline_packages()
mu/virtual_environment.py:465: in install_baseline_packages
    wheels.download()
mu/wheels/__init__.py:48: in download
    check=True,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

input = None, capture_output = False, timeout = None, check = True
popenargs = (['/github/workspace/venv/bin/python', '-m', 'pip', 'download', '--destination-directory', '/github/workspace/mu/wheels', ...],)
kwargs = {}, process = <subprocess.Popen object at 0xf454faf0>, stdout = None
stderr = None, retcode = 1

    def run(*popenargs,
            input=None, capture_output=False, timeout=None, check=False, **kwargs):
        """Run command with arguments and return a CompletedProcess instance.
    
        The returned instance will have attributes args, returncode, stdout and
        stderr. By default, stdout and stderr are not captured, and those attributes
        will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them.
    
        If check is True and the exit code was non-zero, it raises a
        CalledProcessError. The CalledProcessError object will have the return code
        in the returncode attribute, and output & stderr attributes if those streams
        were captured.
    
        If timeout is given, and the process takes too long, a TimeoutExpired
        exception will be raised.
    
        There is an optional argument "input", allowing you to
        pass bytes or a string to the subprocess's stdin.  If you use this argument
        you may not also use the Popen constructor's "stdin" argument, as
        it will be used internally.
    
        By default, all communication is in bytes, and therefore any "input" should
        be bytes, and the stdout and stderr will be bytes. If in text mode, any
        "input" should be a string, and stdout and stderr will be strings decoded
        according to locale encoding, or by "encoding" if set. Text mode is
        triggered by setting any of text, encoding, errors or universal_newlines.
    
        The other arguments are the same as for the Popen constructor.
        """
        if input is not None:
            if 'stdin' in kwargs:
                raise ValueError('stdin and input arguments may not both be used.')
            kwargs['stdin'] = PIPE
    
        if capture_output:
            if ('stdout' in kwargs) or ('stderr' in kwargs):
                raise ValueError('stdout and stderr arguments may not be used '
                                 'with capture_output.')
            kwargs['stdout'] = PIPE
            kwargs['stderr'] = PIPE
    
        with Popen(*popenargs, **kwargs) as process:
            try:
                stdout, stderr = process.communicate(input, timeout=timeout)
            except TimeoutExpired:
                process.kill()
                stdout, stderr = process.communicate()
                raise TimeoutExpired(process.args, timeout, output=stdout,
                                     stderr=stderr)
            except:  # Including KeyboardInterrupt, communicate handled that.
                process.kill()
                # We don't call process.wait() as .__exit__ does that for us.
                raise
            retcode = process.poll()
            if check and retcode:
                raise CalledProcessError(retcode, process.args,
>                                        output=stdout, stderr=stderr)
E               subprocess.CalledProcessError: Command '['/github/workspace/venv/bin/python', '-m', 'pip', 'download', '--destination-directory', '/github/workspace/mu/wheels', 'git+https://github.com/ntoll/pgzero.git@5bcfff44fb50a30f9c0194c76099786d9e31d906']' returned non-zero exit status 1.

/usr/lib/python3.7/subprocess.py:487: CalledProcessError
----------------------------- Captured stdout call -----------------------------
Already using interpreter /github/workspace/venv/bin/python
Path not in prefix '/github/workspace/venv/include/python3.7m' '/usr'
download:package ('git+https://github.com/ntoll/pgzero.git@5bcfff44fb50a30f9c0194c76099786d9e31d906', '')
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/ntoll/pgzero.git@5bcfff44fb50a30f9c0194c76099786d9e31d906
  Cloning https://github.com/ntoll/pgzero.git (to revision 5bcfff44fb50a30f9c0194c76099786d9e31d906) to /tmp/pip-req-build-b9eiktgl
----------------------------- Captured stderr call -----------------------------
  Running command git clone -q https://github.com/ntoll/pgzero.git /tmp/pip-req-build-b9eiktgl
  ERROR: Error [Errno 2] No such file or directory: 'git': 'git' while executing command git clone -q https://github.com/ntoll/pgzero.git /tmp/pip-req-build-b9eiktgl
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
------------------------------ Captured log call -------------------------------
WARNING  mu.virtual_environment:virtual_environment.py:463 No wheels found in /github/workspace/mu/wheels; downloading...

----------- coverage: platform linux, python 3.7.3-final-0 -----------
Name                         Stmts   Miss  Cover   Missing
----------------------------------------------------------
mu/__init__.py                   7      0   100%
mu/app.py                      101      0   100%
mu/config.py                     8      0   100%
mu/debugger/client.py          200      0   100%
mu/debugger/config.py            1      0   100%
mu/debugger/runner.py          257      0   100%
mu/debugger/utils.py            11      0   100%
mu/i18n.py                       6      0   100%
mu/interface/__init__.py         2      0   100%
mu/interface/dialogs.py        321     18    94%   246-254, 330-331, 617-621, 627-628, 635-644
mu/interface/editor.py         269      0   100%
mu/interface/main.py           606      6    99%   673, 725-726, 738, 797, 841
mu/interface/panes.py          817      5    99%   1304-1305, 1311-1313
mu/interface/themes.py         192      0   100%
mu/interface/widgets.py         79      0   100%
mu/logic.py                    827      4    99%   887, 1100-1104
mu/modes/__init__.py            11      0   100%
mu/modes/api/__init__.py        11      0   100%
mu/modes/api/adafruit.py         1      0   100%
mu/modes/api/esp.py              1      0   100%
mu/modes/api/flask.py            1      0   100%
mu/modes/api/lego.py             1      0   100%
mu/modes/api/microbit.py         1      0   100%
mu/modes/api/pi.py               1      0   100%
mu/modes/api/pyboard.py          1      0   100%
mu/modes/api/pygamezero.py       1      0   100%
mu/modes/api/python3.py          1      0   100%
mu/modes/api/shared.py           1      0   100%
mu/modes/base.py               340      0   100%
mu/modes/circuitpython.py       69      0   100%
mu/modes/debugger.py           182      0   100%
mu/modes/esp.py                105      0   100%
mu/modes/lego.py                14      0   100%
mu/modes/microbit.py           313     17    95%   78-90, 335-344, 373-377, 390-397
mu/modes/pico.py                14      0   100%
mu/modes/pyboard.py             58      0   100%
mu/modes/pygamezero.py          65      0   100%
mu/modes/python3.py            180     10    94%   42-58
mu/modes/web.py                107      0   100%
mu/resources/__init__.py        17      0   100%
mu/settings.py                 122      0   100%
mu/virtual_environment.py      213     16    92%   118, 121, 124, 174-182, 294, 327, 330, 378, 388, 481
----------------------------------------------------------
TOTAL                         5535     76    99%

=========================== short test summary info ============================
FAILED tests/test_logic.py::test_editor_restore_session_existing_runtime - su...
============ 1 failed, 988 passed, 19 skipped in 125.54s (0:02:05) =============

Check

Clean

black

flake8

coverage
```

**Comment by carlosperate** [comment]
Pygame for Buster in PiWheels is there:
image

**Comment by carlosperate** [comment]
Thankfully the Arm CI job runs from a Docker image, so I was able to run that image locally and mess in the command line to figure out the issue. Turned out to be a simple one, git wasn't installed and it failed to fetch the `pgzero` package from GitHub.

Added that and now the Arm tests are passing:
- https://github.com/mu-editor/mu/pull/1269/checks?check_run_id=1818446964
- https://github.com/mu-editor/mu/pull/1269/checks?check_run_id=1818446471

**Review by tjguk — COMMENTED** [review]
I'll have to slightly rejig the `download` code here (and probably the code in `VirtualEnvironment` which determines the base packages) to allow the git form of pip identifier to have a name

**Comment by tjguk** [comment]
I think the simplest thing is to make the first element be always the unqualified name, useful for display purposes; and the second element always be a full pip identifier, eg:

```
(
  'flask', 'flask==1.1.2',
  'pgzero', "git+https://github.com/ntoll/pgzero.git"
        "@5bcfff44fb50a30f9c0194c76099786d9e31d906",
  ...
)
```

**Comment by carlosperate** [comment]
Okay, then if everything else looks good let's merge this, since it includes a fix to the CI as well, and you can do the update on top of this?

**Comment by carlosperate** [comment]
Otherwise you can just push changes to this branch for the PR

**Comment by tjguk** [comment]
Go ahead and merge, @carlosperate  -- I don't have time to do much at the moment and I'd rather move this forward. I'll rebase off this when I can get back to my own PR. Thx

**Comment by carlosperate** [comment]
Okay, sounds good, thank Tim!

**Pull request merged**
