### PR TITLE
Travis: Run tests in arm64 architecture

### PR DESCRIPTION
**Pull request by carlosperate**
This is not ready for merge quite yet, but it is getting there, it needs PR https://github.com/mu-editor/mu/pull/1102 to be merged first.

This PR adds the arm64 architecture to Travis CI to run the tests. This will be useful to help make sure we don't break things on Raspberry Pi, and the environmental markers edited in this PR should also enable being able to run Mu in other single board computers, possibly on Arm Chromebooks, and on systems like the [Pinebook Pro](https://www.pine64.org/pinebook-pro/).

Also fixes https://github.com/mu-editor/mu/issues/826.

### CODE REVIEW

**Comment by carlosperate** [comment]
Currently failing from updates introduced in https://github.com/mu-editor/mu/pull/1100.
@dybber do you know if there is an alternative to `QtProcess.errorOccurred()` (introduced in Qt5.6) available in Qt5.5.1?

**Comment by dybber** [comment]
Seems like it was renamed from `QProcess.error` to `QProcess.errorOccurred` at some point.

See: https://doc.qt.io/archives/qt-5.5/qprocess.html

And now: https://doc.qt.io/qt-5/qprocess.html

**Comment by carlosperate** [comment]
Thanks Martin!
With the changed signal method name the tests seems to work fine.  However I am not sure how to manually trigger an error to test that code-path. I tried disconnecting the board during flashing and raising an exception within the esptool itself by editing the module. The errors caused are captured correctly in the text area, but not via `esptool_error()` method call.

I guess the signal only gets raised when the actual process crashes, any thoughts on how that could be forced?

**Comment by dybber** [comment]
I'm on my phone this weekend, so I can only browse the documentation. 

What if the esptool just isn't there, then it should fail with a `QProcess.FailedToStart`

**Comment by dybber** [comment]
Just an idea, what if you change the `PATH` environment variable, to provoke the `QProcess.FailedToStart`?

**Comment by carlosperate** [comment]
Changing Path, not having esptool available when it tries to running or forcing Mu to look at the wrong module all caused issues that were caught somewhere else before the QProcess.error could be trigger.

However, manually editing esptool and using [ctypes to make the Python process crash](https://stackoverflow.com/a/42544856/775259) did the trick, and I can confirm that both `QProcess.error` and `QProcess.error` capture that crash.

**Comment by dybber** [comment]
Great!

**Pull request merged**
