### PR TITLE
CI: Remove macOS from Travis test runs.

### PR DESCRIPTION
**Pull request by carlosperate**
To significantly reduce the number of free credits used per build.

Now that we have GitHub Actions running in this repository the macOS builds are done there.

### CODE REVIEW

**Comment by carlosperate** [comment]
Even if the current Travis PR check hasn't run we have the pass from the commit push run:
https://travis-ci.org/github/mu-editor/mu/builds/748799075

I'll merge this now because we've been having more activity in the repo and we are close to consume all the Travis credits for the month.

@tjguk @dybber if you could rebase your branches or merge master that'd be good too.

**Comment by tjguk** [comment]
@carlosperate rebased; thanks

**Comment by dybber** [comment]
Will do.

**Comment by dybber** [comment]
Done.

**Pull request merged**
