### PR TITLE
Issue212 selection highlights

### PR DESCRIPTION
**Pull request by tjguk**
This PR is for the issues discussed in #212 but it builds on the (currently unmerged) work in #209

### CODE REVIEW

**Comment by ntoll** [comment]
Build still failing due to PEP8. :-(

**Comment by tjguk** [comment]
Hmmm. I ran all the make checks over it. Ok; I'll have a look.

**Comment by tjguk** [comment]
Perhaps I'm misunderstanding the output: it looks to me as though the overall merge is passing, but that individual commits are failing -- which they will, since they precede other commits which are exactly fixing up PEP8 errors. Should I have rebased before pushing the PR?

**Comment by ntoll** [comment]
Apologies... looks like it was Travis that had the collywobbles. I hit it with the proverbial spanner and it's gone green. ;-)

**Comment by ntoll** [comment]
Looking at coverage, there's a couple of branches in the code that are not exercised. I'll add/massage the tests to get us back to 100%.

**Pull request merged**
