### PR TITLE
Check if script > 8k

### PR DESCRIPTION
**Pull request by ZanderBrown**
Okay so completely untested & quite possibly over simplified but here it is.

Check if the script is greater than 8k before flashing. Hopefully closing #152 

A workaround this 8k limit maybe to attempt to strip out comments in code before flashing?

### CODE REVIEW

**Comment by ZanderBrown** [comment]
This should probably be implemented in uflash as well

**Comment by carlosperate** [comment]
There is a style error:

    mu/logic.py:322:1: W293 blank line contains whitespace
    make: *** [pycodestyle] Error 1

At the moment only the OS X server is running the tests.

**Comment by ZanderBrown** [comment]
hopefully that'll clear it up

**Comment by ntoll** [comment]
Great stuff! I'd love to merge this but Travis is complaining and it appears to be some sort of configuration problem..? @carlosperate..?

**Comment by carlosperate** [comment]
It like it's a "code issue" reported by pyflakes, although I cannot see the offending problem on the code itself, maybe an invisible characters?
https://travis-ci.org/mu-editor/mu/jobs/161134091#L313

@ZanderBrown could you try to run the `make check` on your machine to see if you can replicate locally?

**Comment by carlosperate** [comment]
Actually, if I copy the offending line into an editor with ANSI or UTF-8 enconding it pastes the following:

```
if len(python_script) >= ?8192:
```

So there is a character there before the `8192`.

**Comment by ZanderBrown** [comment]
hopefully all invisible characters are gone

**Comment by ntoll** [comment]
Woop woop. :-)

**Comment by carlosperate** [comment]
>Build mu 1.0.277 failed

>Commit 0ffbbbeaee by Zander on 9/20/2016 3:08 PM:
>Travis: i dare you to reject this

https://ci.appveyor.com/project/carlosperate/mu/build/1.0.277

Looks like you angered the other CI god  :scream:

No worries though, it a pyqt5_installer.exe download timeout, which happens sometimes, it should be fine the next time it tries.

**Comment by ZanderBrown** [comment]
seems to be fine now.

Possibly investigate https://liftoff.github.io/pyminifier/ or similar to avoid anyone seeing this message of doom? Alternatively fix the runtime 😄

**Comment by carlosperate** [comment]
Nothing to do with python or the application, just appveyor failing to fetch a file online. I'll increase the timeout a little bit anyway, that should give it a bit more breath room to download it.
If I have the time I'll look into caching the file to preserve it between builds.

**Comment by ZanderBrown** [comment]
Looking at why >8k is a problem it would appear the cause would appear to be quite simple:

The Micro:Bit has 16k memory
The MicroPython runtime is now > 7k

7k + 8k is very close to 16k so it appears that the problem here is that we a running out of memory. Not a problem you get very often these days.

So I get the feeling we are going to need to revisit this with every update to the runtime.

**Comment by ntoll** [comment]
Upstream MicroPython are addressing the limited amount of RAM. In this specific instance I believe the problem is that >8k causes the hex of the Python script to leak over other parts of the hex thus causing problems.

**Comment by carlosperate** [comment]
This is something we could calculate in uFlash and expose the available flash memory to mu, which would be better than having that magic number .

**Comment by ZanderBrown** [comment]
that would simplify. as I said this was only a quick fix

**Pull request merged**
