### PR TITLE
Fix selection match highlights with non-ASCII editor contents.

### PR DESCRIPTION
**Pull request by tmontes**
Addresses issue #725, please see my [notes there](
https://github.com/mu-editor/mu/issues/725#issuecomment-454389761).

### CODE REVIEW

**Comment by tmontes** [comment]
Progress:
* Included one related fix: highlighting matched, non-ASCII selections as well.
  * Simplified the `RE_VALID_WORD` regular expression to `^\w+$`.
  * Per [Python re's module docs](https://docs.python.org/3/library/re.html), the `\w` class *"includes most characters that can be part of a word in any language, as well as numbers and the underscore"*, which suits the use case perfectly, AFAICT.
  * For some reason, the previous regular expression allowed for empty strings: am I missing something?
* Implemented two tests:
  * Test that selection match highlights work for ASCII only words in a document with non-ASCII characters (as reported in #725).
  * Test that the selection match highlights work for non-ASCII only words.
  * Both passing on my dev system.

Let's see what Travis and AppVeyor have to say...

**Comment by ntoll** [comment]
I know how to fix the CI fails (basically, rebase from current master).

I've taken a look with eyeball Mk.1 and this looks good. I'll try to take a proper look by the end of the weekend, and hopefully merge.

Thank you for the contribution @tmontes..!

**Comment by tjguk** [comment]
If I can I'll try to look at this this afternoon (since it's my code which is failing :) ). But if you're happy to go ahead and merge please do so without waiting for me. I can always pick up issues afterwards if there are any.

**Comment by tmontes** [comment]
@ntoll, @tjguk, thanks for taking a look at this. :)

I "blindly" went for the "update branch with current master" but AppVeyor and Travis are still failing. I then went digging deeper:

* Travis failure analysis:
  * `pycodestyle` is complaining about lines [142](https://github.com/mu-editor/mu/blob/3eaa305ba62e5f4c51057eb5fb84270bdee033f2/mu/debugger/runner.py#L142) and [144](https://github.com/mu-editor/mu/blob/3eaa305ba62e5f4c51057eb5fb84270bdee033f2/mu/debugger/runner.py#L144) which it says are over-indented (they are, indeed, and have been so since mid 2018, commit af47bc1b).
  * It didn't fail before on CI neither on my local check though. Motive: `pycodestyle` has recently been updated and Travis brought in the newer version, 2.5.0, just released on 2019-01-29, that now includes a new check for "E117: Over-indented code blocks" ([change log here](https://pycodestyle.readthedocs.io/en/latest/developer.html#changes)).

* AppVeyor failure analysis:
  * Seems like it fails complaining that `tests\debugger\test_client.py:579: use ==/!= to compare str, bytes, and int literals` [here](https://ci.appveyor.com/project/carlosperate/mu/builds/22074452#L394), triggered by the `make win64` which will run the equivalent of a `make check` as a dependency (am I reading this right?). The log omits further details that I could use to pinpoint why this hasn't failed before.
  * Interestingly, [line 579](https://github.com/mu-editor/mu/blob/3eaa305ba62e5f4c51057eb5fb84270bdee033f2/tests/debugger/test_client.py#L579) in `tests/debugger/test_client.py` does an assertion / comparison which I find odd. The code reads `assert bp.ignore is 5` and the message makes sense. Why is it not using `==`?

Way forward:
* Fixing Travis should be handled outside of this PR, with a single-purpose issue+PR (PR only?) that fixes the over-indented code blocks in `debugger/runner.py`.
* With regards to AppVeyor, my guess is, again, something outside of this PR's scope needs work. Even though this could probably be addressed by changing the `is` operator to an `==` one, I'm not sure i) why the `is` is being used, and, ii), more importantly, why this hasn't failed before. (or maybe I'm reading the AppVeyor log wrongly!).

Summary:
* Both these CI failures seem unrelated to the PR itself.
* Let's hold on until both are fixed at the "project level", I say...

Hopefully someone can chime in with more feedback on this. Thanks!

**Comment by tmontes** [comment]
PS: @ntoll, I see you fixed the indentation the newer 2.5.0 `pycodestyle` is complaining about in PR #749, commit 54c50d55a865b250a3b9845e80ff292b63f2e055. Maybe that's why you suggested rebasing from master?

**Comment by carlosperate** [comment]
>I thought the RE_VALID_WORD might have been mine as well, but I simply inherited and didn't look too closely. I think the original was @carlosperate -- so he might have some notion of why zero-length strings were allowed.

It's been way too long since I wrote that, so honestly cannot remember if there was a special reason why zero-length strings should be allowed, but it doesn't sound like there is, so the new regex looks good.

**Comment by tmontes** [comment]
Regarding the AppVeyor failure I commented on, from the just released Python 3.8.0a1 change log:

> [bpo-34850](
https://bugs.python.org/issue34850): The compiler now produces a [`SyntaxWarning`](
https://docs.python.org/3.8/library/exceptions.html#SyntaxWarning) when identity checks (`is` and `is not`) are used with certain types of literals (e.g. strings, ints). These can often work by accident in CPython, but are not guaranteed by the language spec. The warning advises users to use equality tests (`==` and `!=`) instead.

So, yes, maybe the [`bp.ignore is 5` assertion in `tests/debugger/test_client.py`:579](
https://github.com/mu-editor/mu/blob/3eaa305ba62e5f4c51057eb5fb84270bdee033f2/tests/debugger/test_client.py#L579) should be changed.

Thoughts?

**Comment by ntoll** [comment]
Merged! Thank you for fixing this folks!

**Pull request merged**
