### PR TITLE
WiP: Move child process shutdown from modes to PythonProcessPane

### PR DESCRIPTION
**Pull request by dybber**
This is work in progress and needs to be tested across platforms. The goal is to solve both #1004 and #1236

### CODE REVIEW

**Comment by tjguk** [comment]
I've only looked cursorily at the code, but I'm +1 on the general idea here.

**Comment by ntoll** [comment]
@dybber this is still marked as WiP. Anything need doing to un-WiP it into a ready-to-review-and-test PR..? :+1:

**Comment by ntoll** [comment]
Hi @dybber and @tjguk 

I've taken a quick look at the code and I'm also :+1: on this with the following caveat: The orphaned child processes from #1004 no longer appear on Windows.

@dybber I'm also painfully aware that you've marked this as WiP. What more were you hoping to do..?

**Comment by ntoll** [comment]
OK, I've tested this on both Windows and Linux and it appears to do exactly what it says. Merging.

**Pull request merged**
