### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by gquintana**

### CODE REVIEW

**Comment by ntoll** [comment]
Hi @gquintana, Many thanks for the PR, we *really* appreciate your efforts. Like the other translations I'm going to leave this PR unmerged until the UI is in a final state for 1.0 (in a matter of weeks). At that point I'll ping everybody just so the PR can be re-checked in light of changes.

Thank you!

**Comment by ZanderBrown** [comment]
@ntoll perhaps add this to the 1.0 milestone?

**Comment by gquintana** [comment]
Alright @ntoll,  ping me when code is stable enough. I'll update this pull request.

**Comment by gquintana** [comment]
About "OK/Cancel" the problem is even more general, the whole "Open file" dialog is in english 
mu-editor-fr-open-file

Other problems I noticed:
* When I click on Help, the browser opens with URL https://codewith.mu/fr/help/1.0 and a 404 error. A redirect to the english page seems more appropriate, at least until documentation is translated in french :-)
* Some strings are duplicated for instance "Please make sure the device is plugged into this computer *"

**Comment by ZanderBrown** [comment]
The open file dialog is called through Qt (and that looks like a themed Gtk3 dialog to me) so increasingly gets into "not our problem" territory as the Open/Close text is in a Gtk3 dialog generated by Qt with Qt internal strings.

What's your system language?

**Comment by gquintana** [comment]
My system language is french.
May be there is a global a option to tell Qt which language to use. Where
should I search?

**Comment by ZanderBrown** [comment]
Maybe onto something, hopefully you can test that in a bit

**Comment by ZanderBrown** [comment]
If possible could you test [my branch](https://github.com/ZanderBrown/mu/tree/base/modal-dialogs)?

**Comment by gquintana** [comment]
I don't see any change. Sorry.

Is it possible that Qt french translation is not installed on my system? Where can I look at available translations?

**Comment by ZanderBrown** [comment]
Hmm, 2 Qt quirks in a single day.

Not sure how to proceed from here

**Comment by gquintana** [comment]
Other problem: whereas my french translation is properly loaded on Linux, it remains in English on Windows 7 32bits with same code :-(

**Comment by ntoll** [comment]
Hi @gquintana the UI is now complete so please check and revise. Thank you for your contribution. I'd love to get this into the release candidate at the end of the week! ;-)

**Comment by gquintana** [comment]
Could you use positional or named parameters in message, for instance:
```
Replaced {} matches of "{}" with "{}".
```
Parameters are not necessary in the same order in all languages

**Comment by gquintana** [comment]
@ntoll Translation updated

**Comment by ZanderBrown** [comment]
@gquintana good call on different order parameters, very easy to get stuck in English structure sometimes

**Comment by ntoll** [comment]
Merci beaucoup! :cow: :heart: :fr:

**Comment by ntoll** [comment]
french_mu

I love the French word for "debugger". :-D

**Comment by gquintana** [comment]
:-) Well sometimes no translation is better than a bad translation (how to
translate REPL?). I don't use the french verb Déboguer butI checked it is
in the french dictionary. I won't argue if someone prefers the English verb.

**Comment by ZanderBrown** [comment]
Bing Translate suggests LEIB (lire évaluer impression boucle), but REPL may be better

**Comment by ntoll** [comment]
And this one too: https://github.com/mu-editor/mu/blob/master/mu/interface/main.py#L353 (thanks for the spot!)

**Pull request merged**
