### PR TITLE
Fix for #1299 with microbit minify toggle

### PR DESCRIPTION
**Pull request by dybber**
This fixes issue #1299

### CODE REVIEW

**Comment by ntoll** [comment]
@dybber could you run `make tidy` and push again. It looks like that is the cause of the failing tests.

**Comment by dybber** [comment]
> @dybber could you run `make tidy` and push again. It looks like that is the cause of the failing tests.

Done. Previously "make check" also checked for PEP8 issues like these, but now it seems I only get these warnings after I make the pull request. I will have to remember to run both `make check` and `make tidy` in the future before pushing

**Comment by carlosperate** [comment]
> Done. Previously "make check" also checked for PEP8 issues like these, but now it seems I only get these warnings after I make the pull request. I will have to remember to run both make check and make tidy in the future before pushing

The Makefile should only skip these tests if you are running in Python 3.5, as black is >=3.6. Is that the version you are running? Otherwise let's open a new issue.

**Comment by dybber** [comment]
> > Done. Previously "make check" also checked for PEP8 issues like these, but now it seems I only get these warnings after I make the pull request. I will have to remember to run both make check and make tidy in the future before pushing
> 
> The Makefile should only skip these tests if you are running in Python 3.5, as black is >=3.6. Is that the version you are running? Otherwise let's open a new issue.

Oh sorry, maybe I used `make coverage` not `make check`, my bad. I will immediately add a pre-commit hook to automatically run `make check` in the future.

**Comment by carlosperate** [comment]
No worries, the makefiles were updated recently to ensure `make check` doesn't fail in 3.5 (by skipping black) and was wondering if maybe there was still an issue.

**Pull request merged**
