### PR TITLE
Chdir before run

### PR DESCRIPTION
**Pull request by tjguk**
First pass at a fix for #765 -- each mode sets the cwd of its subprocess to the dirname of the code file. Ad hoc tests seem to succeed.

### CODE REVIEW

**Comment by tjguk** [comment]
I've updated the existing run_xxx tests (since they needed to be fixed anyway). There didn't seem point in adding other tests, but I can do if people want.

**Comment by tjguk** [comment]
@ntoll I'd like to get this PR into the upcoming release. It's fairly trivial and the tests pass locally. I can't make out what Appveyor / Travis are complaining about? I'm not clear if there's a mechanism for re-running the checks without pushing some trivial update from the PR, so maybe I'll just try to do that

**Comment by ntoll** [comment]
@tjguk if you rebase with master the CI problems should disappear. Both @tmontes and I had our fights with Travis and Appveyor last week, but master is building fine (and thus, so should this PR when rebased). IYSWIM :-)

**Comment by tjguk** [comment]
@ntoll Thanks; I thought I just had but clearly something's out of kilter. I'll probably do a fresh clone and try again

**Comment by ntoll** [comment]
+1 and thanks! :-)

**Comment by tjguk** [comment]
Still not doing it. I'll try again at home this pm on the machine where I actually created the branch/PR.

**Comment by ntoll** [comment]
+1 :-)

**Comment by tjguk** [comment]
At least the branch is pushing. But I'm now getting check/test failures which I don't think are of my own making. I've just synced from master into my branch so it may be there's some sort of interaction there. I'll have a dig

**Comment by ntoll** [comment]
Ugh... I think those failures may be to do with my fix relating to the newline PR. Ugh... I'll try again now.

**Comment by ntoll** [comment]
OK... I believe my change now in master (f9ab6671ea) fixes the failing build. Sorry about that. :-(

**Comment by ntoll** [comment]
OK... I believe my change now in master (f9ab6671ea) fixes the failing build. Sorry about that. :-(

**Comment by tjguk** [comment]
Looks like Travis & AppVeyor are happy. LGTM still thinking...

Turns out that I added to my own confusion by syncing my master from upstream master but then failing to sync my branch from my master!

**Comment by ntoll** [comment]
There's a reason it's called "GIT". :-)

When it's all green, I'll merge. Thank you!

**Comment by ntoll** [comment]
All merged. Thanks!

**Pull request merged**
