### PR TITLE
Pip fail2

### PR DESCRIPTION
**Pull request by tjguk**
Force the `Pip` object to recreate its internal QProcess object on every run. This sidesteps the issue where it's first invoked as part of a worker thread during the Splash screen, causing every later invocation to run cross-thread

### CODE REVIEW

**Comment by ntoll** [comment]
This looks great. I just tested it and I can confirm that no QThread warnings appear when Mu is setting up a virtual environment on first run. Furthermore, it appears that I can install packages *on first run* (fixing #1358).

However, I have a request... the current logging in the splash screen on first run is rather opaque (see below). Could we re-write the logging so they're more informative, confidence building, friendly..? :-)

mu_logging_opaque

**Comment by tjguk** [comment]
Thanks @ntoll  -- yes, that was all interim debug logging while I was trying to narrow stuff down. I've removed most of it now. In fact, I was going to make a suggestion back in the other direction that we limit the splash logging handler to show only INFO and higher. (ie to ignore DEBUG). At that point we can certainly refine the INFO output so it tells a clearer story.

**Comment by tjguk** [comment]
So while we've definitely got the culprit, finding the eventual solution will take a little working through. 

The long and short is that we need to ensure that, when Pip runs *after* `create_and_ensure` it uses a different QProcess object from the one used *inside* `create_and_ensure`. We can definitely do that crudely -- basically extending the quick fix I did earlier to prove the concept. But I'd like to do it more elegantly.

However... that's interacting awkwardly with the usual Qt problem: Python object lifetimes. IOW the ideal solution is a long-lived `Pip.QProcess` object, but one that distinguishes between being in a thread or not.

**Comment by tjguk** [comment]
Pushed a working solution. I'll add a test later, but let's see if the tests pass ok.

**Pull request merged**
