### PR TITLE
Modify some zh_CN translations that I thought needed to be modify

### PR DESCRIPTION
**Pull request by Aliceljm1**
Thanks to the two  contributors translation work,  I read the translations carefully, and I thought some of them would confuse my students, and I revised some of them, and asked the students to give their opinion, and of course they don't know submit the code, so I did that. I think they have qualified to speak on this issue :)

### CODE REVIEW

**Comment by JohnGuan** [comment]
Great! Thank you for your comments and contributions! The translation file of the latest pull request has not been merged, and this submission may return a conflict. I think I can add your changes to my latest pull request. And thank you for your contribution there? What do you think?

**Comment by Aliceljm1** [comment]
@JohnGuan , I‘m ok with that, I'm not familiar with the current Mu check code  process. Now We have a problem that the students we teach they are young, they cannot understand English results very well, and it is not easy to solve problems independently. If there is a translation for check code results ,it's would be very great for the Learners' who's mother language is not English ,by the way We Have a free python class in Hefei China, and I am one of the teacher. Nicholas sent a post here [http://madewith.mu/mu/users/2018/10/31/ni-hao-mu.html](url)

**Comment by JohnGuan** [comment]
@Aliceljm1 I am translating content such as document strings, error messages, and so on. If you are interested, you can work together. I teach AI, Python and Raspberry Pi in Shanghai. At the same time, I am also trying to run a Chinese community of mu and python beginners.

**Comment by Aliceljm1** [comment]
@JohnGuan 哎呦不错哦，看来你是专职老师，我们的python课程是公司组织的活动，我供职于一家教育公司，公司组织这个活动的一开始是想让团队能够真实的体验教学场景，有机会当老师，提升认知，而现在我感觉主要是让孩子们能够在学习编程当中有所收获，如果是翻译一些软件内容我还是可以帮忙的。另外我想请教你下，对于代码检查的提示给出翻译结果目前是可行的吗？这一点目前对于低年级学生而言是非常重要的，看不懂错误提示会造成很大的困扰和障碍。

**Comment by JohnGuan** [comment]
@Aliceljm1 理论上字符串都是可以翻译的，编辑器部分目前是有标准翻译方法的，比较好操作。报错这部分是Python解释器的产生的，这部分得看情况。我的目标也是尽可能多的翻译这些信息。

**Comment by Aliceljm1** [comment]
> @Aliceljm1 理论上字符串都是可以翻译的，编辑器部分目前是有标准翻译方法的，比较好操作。报错这部分是Python解释器的产生的，这部分得看情况。我的目标也是尽可能多的翻译这些信息。

非常期待看到这样的成果，会让Mu更加有亲和力。孩子们看到报错不会那么抓狂了。

**Comment by JohnGuan** [comment]
@Aliceljm1 是的！刚刚我把更新内容更新到之前提交的那个pr里了，这个现在应该可以关闭了。

**Comment by JohnGuan** [comment]
@Aliceljm1 如果你有兴趣做一些关于mu的事情的话，可以加我微信：guanningchuan

**Comment by yonghuming** [comment]
真好

**Pull request closed without merging**
