### PR TITLE
venv: Add macOS Python 3.8 pygame custom wheel for app signing workaround

### PR DESCRIPTION
**Pull request by carlosperate**
More info: https://github.com/mu-editor/mu/issues/1290

Adding this in mu.wheels since it is a lot easier to detect the specific OS and Python version than somewhere else like the Makefile or the CI scripts.
This will use a custom wheel hosted in https://github.com/mu-editor/pygame/releases/tag/2.0.1 

Also updates the CI built executables to use Python 3.8.

### CODE REVIEW

**Comment by carlosperate** [comment]
The wheel downloads correctly from its own entry, but it then fails some kind of hash when processing pgzero:
```
mode_packages: [('pygame', 'https://github.com/mu-editor/pygame/releases/download/2.0.1/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl'), ('pgzero', 'git+https://github.com/ntoll/pgzero.git@5bcfff44fb50a30f9c0194c76099786d9e31d906'), ('Flask', 'flask==1.1.2'), ('pyserial', 'pyserial==3.4'), ('qtconsole', 'qtconsole==4.7.4'), ('nudatus', 'nudatus>=0.0.3')]
Running pip download for pygame / https://github.com/mu-editor/pygame/releases/download/2.0.1/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl
Collecting pygame==2.0.1
  Downloading https://github.com/mu-editor/pygame/releases/download/2.0.1/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl (6.9 MB)
Saved ./mu/wheels/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl
Successfully downloaded pygame

Running pip download for pgzero / git+https://github.com/ntoll/pgzero.git@5bcfff44fb50a30f9c0194c76099786d9e31d906
Collecting git+https://github.com/ntoll/pgzero.git@5bcfff44fb50a30f9c0194c76099786d9e31d906
  Cloning https://github.com/ntoll/pgzero.git (to revision 5bcfff44fb50a30f9c0194c76099786d9e31d906) to /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-emorrusb
  Running command git clone -q https://github.com/ntoll/pgzero.git /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/pip-req-build-emorrusb
  Running command git rev-parse -q --verify 'sha^5bcfff44fb50a30f9c0194c76099786d9e31d906'
  Running command git fetch -q https://github.com/ntoll/pgzero.git 5bcfff44fb50a30f9c0194c76099786d9e31d906
  Running command git checkout -q 5bcfff44fb50a30f9c0194c76099786d9e31d906
Collecting pygame>=1.9.2
  File was already downloaded /Users/runner/work/mu/mu/mu/wheels/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl
  WARNING: Previously-downloaded file /Users/runner/work/mu/mu/mu/wheels/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl has bad hash. Re-downloading.
  Using cached pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl (6.9 MB)
```

And if the pip cache is deleted it still has the same issue:
```
...
Collecting pygame>=1.9.2 (from pgzero==1.2)
  File was already downloaded /Users/runner/work/mu/mu/mu/wheels/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl
  WARNING: Previously-downloaded file /Users/runner/work/mu/mu/mu/wheels/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl has bad hash. Re-downloading.
  Downloading https://files.pythonhosted.org/packages/3a/40/69eebf7145055f51cc90145e547da2b68c454b61ae5df6648fec6a259b2f/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl (6.9MB)
  Saved ./mu/wheels/pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl
```

**Comment by carlosperate** [comment]
Okay, the latest update enables extra flags per dependency, so we can download the `pgzero` wheel without checking the downloaded `pygame` wheel (which otherwise would get downloaded again due to having the wrong hash vs PyPI).

This implementation still has the problem that when the pgzero wheel is created from the source distribution downloaded, it then downloads the PyPI `pygame` wheel again.

**Comment by carlosperate** [comment]
@ntoll I've forked your pgzero fork into the mu-editor org to create this GH release with an attached wheel: https://github.com/mu-editor/pgzero/releases/tag/mu-wheel

Okay, so by installing `pgzero` via this wheel, and with the `--no-index` flag, it resolves the issue mentioned in my last message where building the wheel re-downloaded the `pygame` wheel from PyPI.

I checked the PR CI and the macOS installer finally comes with the hacked `pygame` wheel: https://github.com/mu-editor/mu/actions/runs/573146175 🎉 

So this PR should be ready for a signing test.

**Comment by carlosperate** [comment]
@tjguk as the changes in this PR are mostly in mu.wheels (since the hacked pygame wheel is only for macOS and Python 3.8, so it was easier to conditionally pick this wheel here than in the Makefile), would you be able to review this PR for me?

**Comment by ntoll** [comment]
@carlosperate amazing work..! :+1:

I'll try a build based on this branch later today (probably lunch).

This is still marked as draft. Is that still the case, or can I merge..?

**Review by tjguk — APPROVED** [review]
Just on a quick inspection, that looks fine to me, @carlosperate

**Comment by carlosperate** [comment]
Thanks Tim!
I've marked this PR as ready, some of the tests are failing due to https://github.com/mu-editor/mu/issues/1266, so I'll restart them until they all conclude.

**Comment by carlosperate** [comment]
All GH CI tests are passing, so PR is ready to merge after the signing test.

**Comment by ntoll** [comment]
:+1: Just need to wait for Mary to finish with her MacBook. ;-) Will be done this evening at latest.

**Comment by tjguk** [comment]
@carlosperate I'm just syncing up to date before making changes to venv. Is this PR ready to merge now?

**Comment by carlosperate** [comment]
Yeah, I've just merged. App signing has been done successfully from this PR and enough testing has been done to ensure pygame with pygame zero is running.

**Pull request merged**
