### PR TITLE
venv: Add installed packages to log in single entry.

### PR DESCRIPTION
**Pull request by carlosperate**
Tiny PR to make the log a bit less vertically long. It makes checking the log a bit easier when debugging.

With this change it shows:
```
2021-01-31 19:30:15,957 - mu.virtual_environment:523(installed_packages) INFO: ['appnope', 'backcall', 'click', 'decorator', 'Flask', 'ipykernel', 'ipython', 'ipython-genutils', 'itsdangerous', 'jedi', 'Jinja2', 'jupyter-client', 'jupyter-core', 'MarkupSafe', 'nudatus', 'numpy', 'parso', 'pexpect', 'pgzero', 'pickleshare', 'pip', 'prompt-toolkit', 'ptyprocess', 'pygame', 'Pygments', 'pyserial', 'python-dateutil', 'pyzmq', 'qtconsole', 'QtPy', 'setuptools', 'six', 'tornado', 'traitlets', 'wcwidth', 'Werkzeug', 'wheel']
```

Instead of:
```
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: appnope
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: backcall
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: click
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: decorator
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: Flask
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: ipykernel
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: ipython
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: ipython-genutils
2021-01-31 18:50:38,898 - mu.virtual_environment:521(installed_packages) INFO: itsdangerous
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: jedi
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: Jinja2
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: jupyter-client
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: jupyter-core
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: MarkupSafe
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: nudatus
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: numpy
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: parso
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: pexpect
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: pgzero
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: pickleshare
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: pip
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: prompt-toolkit
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: ptyprocess
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: pygame
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: Pygments
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: pyserial
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: python-dateutil
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: pyzmq
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: qtconsole
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: QtPy
2021-01-31 18:50:38,899 - mu.virtual_environment:521(installed_packages) INFO: setuptools
2021-01-31 18:50:38,900 - mu.virtual_environment:521(installed_packages) INFO: six
2021-01-31 18:50:38,900 - mu.virtual_environment:521(installed_packages) INFO: tornado
2021-01-31 18:50:38,900 - mu.virtual_environment:521(installed_packages) INFO: traitlets
2021-01-31 18:50:38,900 - mu.virtual_environment:521(installed_packages) INFO: wcwidth
2021-01-31 18:50:38,900 - mu.virtual_environment:521(installed_packages) INFO: Werkzeug
2021-01-31 18:50:38,900 - mu.virtual_environment:521(installed_packages) INFO: wheel
```

### CODE REVIEW

**Review by tjguk — APPROVED** [review]
Happy to go with this, Carlos. TBH it's a bit 50:50; if you actually want to see what packages are being installed, vertical is better. If you usually don't, then agree that horizontal is less "noisy".

**Comment by carlosperate** [comment]
Yeah, that's true.
I think for bug reports specially we are likely to ask users to perform the buggy action and then send us the log, and in those cases the data before the packages might be more relevant.

Thanks for the review!
Not sure why the GH Actions are all stuck, I'll have a look.

**Comment by carlosperate** [comment]
Had to cancel some test runs that were "stock" after 4h. I'll review the CI state in the morning in case it happens again.

**Comment by carlosperate** [comment]
The Python 3.8 in macOS is failing for the reasons listed in https://github.com/mu-editor/mu/issues/1266, all other tests pass, so I'll merge, thanks Tim!

**Pull request merged**
