### PR TITLE
Added support for CH9102 in ESP mode

### PR DESCRIPTION
**Pull request by sankarcheppali**
Added support for CH9102 USB-Serial chip

https://cdn-learn.adafruit.com/assets/assets/000/111/949/original/CH9102DS1.PDF?1653415979

### CODE REVIEW

**Comment by carlosperate** [comment]
Thanks for the PR @sankarcheppali!
Where did the VID and PID come from? Are those the default values for the chip? Looks like they can also be configured with different values.
Could you provide any links showing ESP boards using this chip?

**Comment by sankarcheppali** [comment]
Hi @carlosperate 
Thanks for the response. 
This is the board I have
https://github.com/Xinyuan-LilyGO/LILYGO-T8/blob/main/Schematic/t8_v1.7.1.pdf

I took the VID,PID from the windows device manager.

**Comment by amaksoft** [comment]
Hello! CH2102 is also used by [M5Stamp C3](https://docs.m5stack.com/en/core/stamp_c3#driver-installation) (There's both driver and schematics that confirm this particular chip usage)

Chip info on [manufacturer website](https://www.wch-ic.com/products/CH9102.html)

To confirm chip's VID:PID
From shell:
```
$ lsusb
Bus 002 Device 001: ID 1a86:55d4 QinHeng Electronics
```
In device manufacturer [Linux driver code](https://github.com/WCHSoftGroup/ch343ser_linux/blob/main/driver/ch343.c#L2038):
```c
static const struct usb_device_id ch343_ids[] = {
        // ... other devices
	{ USB_DEVICE(0x1a86, 0x55d4) },			       /* ch9102 chip */
        // .... other devices
	{}
```

Can we please get this PR merged so that we don't have to patch it locally?

**Comment by Cheppali-Reddy** [comment]
Hello @carlosperate , please let me know if there are any blockers for merging this ?

**Review by carlosperate — APPROVED** [review]
Thanks everyone! This is good to be merged 👍

**Pull request merged**
