### PR TITLE
docs: Add PyQtChars package for Raspberry Pi install instructions

### PR DESCRIPTION
**Pull request by carlosperate**
The package is only available from Buster, so this is noted as well in the docs.

### CODE REVIEW

**Comment by carlosperate** [comment]
@ntoll if you enable GitHub integration in redathedocs we can get temp PR builds of the docs for preview before merging.

**Comment by ntoll** [comment]
Hmm.... I thought I *had* configured GitHub integrations in ReadTheDocs. :-/ Will check/change now. Merging in any case. :-)

**Comment by ntoll** [comment]
Hmm.... just checked... I do have GitHub integration switched on. What exactly am I looking for..?

**Comment by carlosperate** [comment]
You might have to remove and re-add it again. I think the last time I configured it the hooks didn't "install" correctly in an old project.

**Pull request merged**
