### PR TITLE
Add a Read the Docs yaml config file to remove rtd_requirements.txt

### PR DESCRIPTION
**Pull request by carlosperate**
Read the Docs build log from fork: https://readthedocs.org/projects/mu-test-fork/builds/9147829/
HTML output: https://mu-test-fork.readthedocs.io/en/upstream/index.html

To realign with PR https://github.com/mu-editor/mu/pull/779 "Single source of dependency truth" this PR adds a config file for RtD that's able to install dependencies using `pip install .[docs]`, removing the need to have the rtd_requirements.txt file added in 4201338d848e6cdd0911b97e9bca0dba7b0ee0ca.

### CODE REVIEW

**Comment by tjguk** [comment]
Merged; let's watch the build...

**Comment by tjguk** [comment]
Should I see an automatic rebuild on RTD? Not really familiar with the triggering mechanisms here...

**Comment by carlosperate** [comment]
Never used RtD properly before, the `mu-test-fork` is the first project I have set up myself and with the default options it built on each commit to an "active version". Let me have a look at the settings, maybe there is something set up in the `mu` project to only trigger manually.

**Comment by tjguk** [comment]
Thanks. If necessary I can ping @ntoll offline to ask him to force a rebuild

**Comment by carlosperate** [comment]
I couldn't find anything in the RtD  web settings, but when I created the project yesterday it automatically created a webhook to my Mu fork, and looking at https://github.com/mu-editor/mu/settings/hooks we don't have that set up in this repo.
So perhaps all the builds were manually managed so far.

If we want to set it up it'd have to be done by somebody with admin rights to the RtD project:
https://docs.readthedocs.io/en/stable/webhooks.html#webhook-creation

**Comment by ntoll** [comment]
On it..! :-)

**Comment by ntoll** [comment]
OK... it appears to work. I've added a new webhook and I just made a trivial change. I can see the build kick off.

Thank you @carlosperate and @tjguk for making this happen :+1:

**Comment by tjguk** [comment]
Thanks, @ntoll. @carlosperate do you just want to review the build info https://readthedocs.org/projects/mu/builds/9149704/ before we close this one off?

**Comment by ntoll** [comment]
LGTM. Also, this issue was closed when you merged the PR. ;-)

**Comment by tjguk** [comment]
I knew that!

**Comment by carlosperate** [comment]
LGTM as well, except for the "pip installs" the commands called before and after the config file are the same. Thanks @tjguk and @ntoll!

**Pull request merged**
