### PR TITLE
fix for #302 and #281

### PR DESCRIPTION
**Pull request by ladyada**
#302 - still pops up error boxes but at least doesnt quit!
#281 - hack fix for circuitpython not working with qtserial under windows

### CODE REVIEW

**Comment by ntoll** [comment]
@ladyada thanks for this code, I'll run with it and see if I can fix up #302 and #281. Looks like today is going to be a Mu-nday (sorry, but that's too terrible a pun not to actually use). :-)

**Comment by ladyada** [comment]
huzzah! are y'all still generating appveyor exe's for mu, that's are ideal for windows people who are not command-line-pros :)

**Comment by ntoll** [comment]
Funny you should mention that - I'm hoping to get MSI packaging started this week (at the request for RPi foundation). Initial investigations last week show it's definitely possible, if sometimes a dark art. I have some friends who are Windows/Python packaging gurus on hand to answer my questions with emails that start with "here be dragons..." ;-) I'll let you know when I've something that needs testing.

**Comment by ladyada** [comment]
totes, will keep doing PR's!

regarding...is someone working on a plotter substitute for REPL?

**Comment by ntoll** [comment]
Not yet. But it's a good idea and I've not forgotten it. Actually, the "standard Python" REPL is an iPython/Jupyter based REPL in which you can embed plots from, e.g. Matplotlib, so the concept of graphical representation of "stuff" in a REPL should already be familiar.

**Comment by ladyada** [comment]
i was thinking more of a replacement pane, that would liveplot data like arduino ide...?

**Comment by ladyada** [comment]
@ntoll hiya do you need to do more testing before this is merged?

**Comment by ntoll** [comment]
Hi @ladyada, no problem here except time constraints on my part (I've been delivering training all last week). I'm going to find time for a merge-a-thon for beta 13 sometime this week. I expect this change to be in it.

**Comment by ladyada** [comment]
oh yay thank you! thank you!
i have one more small pr to make, to add more VID + PIDs! 
i havent had any time to work on the plotter but im rolling over the code in my head :)

**Comment by ntoll** [comment]
Ooooh... sounds exciting (the plotter).

You've probably already found that VID + PIDs should be added here: https://github.com/mu-editor/mu/blob/master/mu/modes/adafruit.py#L37 for Adafruit boards.

I'm right in the middle of writing up developer docs (currently incomplete version here: https://mu.readthedocs.io/en/latest/index.html) and would love any feedback you have about making it easier for contributors to develop the Mu codebase. Quite understand if I don't hear anything, busy people are busy! :-)

**Comment by ladyada** [comment]
wow these docs are awesome, reading them thru - but they're really clear :) ill read them before adding plotter mode :D

**Comment by BravoDelta151** [comment]
I tested these changes on Windows 10 x64 and did not have any problems accessing or using the REPL 👍

**Pull request merged**
