### PR TITLE
ESP mode: Add VID/PID for other FTDI USB-to-UART chips.

### PR DESCRIPTION
**Pull request by carlosperate**
Fixes https://github.com/mu-editor/mu/issues/851.

@cgarmstr could you check if this branch works for you?

### CODE REVIEW

**Comment by cgarmstr** [comment]
Apologies. I followed the guidelines for Developer Setup https://mu.readthedocs.io/en/latest/setup.html but after doing python run.py got 
ModuleNotFoundError: No module named 'appdirs'
pip install appdirs
fixed that but then got
    from PyQt5.Qsci import QsciScintilla, QsciLexerPython, QsciAPIs
ModuleNotFoundError: No module named 'PyQt5.Qsci'

PS I cheated and put the extra line
        (0x0403, 0x6010),  # FT2232C/D/L/HL/Q (ESP-WROVER-KIT, ESP32DemoBoard)
in esp.py in my existing mu-editor_1.1.0-alpha.1_win64.exe installation.
Mu appears doesn't give a no device connected error, but there is no response to the REPL.

**Comment by carlosperate** [comment]
Okay, let's take this back to issue https://github.com/mu-editor/mu/issues/851 from comment https://github.com/mu-editor/mu/issues/851#issuecomment-500518733.

**Comment by ntoll** [comment]
@carlosperate is this safe to merge..?

**Comment by carlosperate** [comment]
It's not "unsafe", but because the FTDI serial-to-USB bridge creates more than one COM port (one for "debugging" and another for the serial comms), and the first port that Mu uses to attempt a serial connection is not the right one, the user still cannot use the ESP device even with this PR.

The real solution is probably to do as described in #851, and offer a way for the user to select between multiple COM ports.

So we can merge this now and possibly implement that later, or we can leave this open until the other feature is implemented.

**Comment by ntoll** [comment]
@carlosperate let's leave this open until we have a "complete" solution to land in master. Thanks for the clarification.

**Comment by ntoll** [comment]
Any movement on this..?

**Comment by carlosperate** [comment]
Not really, a full solution would be letting the user select a COM port when multiple options are available, and that would require a more significant PR with a new UI window and all.
Unfortunately I probably won't be able to commit the time to do that in the short term.

Feel free to merge, close, or leave open this PR as you see fit.

**Comment by ntoll** [comment]
OK... thank you @carlosperate -- I leave it open for the time being in case others want to work on it. If it's not "fixed" by the move to beta status for 1.1, then I'll close it.

**Comment by dybber** [comment]
Hi all, I have integrated the changes here into #1094, and part of the idea about being able to select devices from a dropdown was just merged (see #1017). I think it's now at a state where we can close this. If people at some point again report issues with this new interface for device selection, we can take a look at it then.

**Pull request closed without merging**
