### PR TITLE
makep.py: Check for return codes

### PR DESCRIPTION
**Pull request by carlosperate**
Fixes https://github.com/mu-editor/mu/issues/464.

check() in make.py wasn't stopping on errors, causing failing builds in AppVeyor to be set as "passed all tests". This PR updates the script to check for the return value of each step in check() and exits early with the correct error code if there is a problem.

### CODE REVIEW

**Comment by tjguk** [comment]
LGTM. Thanks for picking this up

**Comment by ntoll** [comment]
@carlosperate the tests fail on appveyor... Care to check what's going on..?

**Comment by carlosperate** [comment]
The tests have been failing for a while, but AppVeyor didn't indicate so because of the issue resolved in the PR.

**Comment by ntoll** [comment]
@carlosperate OK... I'll fix the tests in the morning.

**Comment by ntoll** [comment]
Fixed. Thanks..!

**Pull request merged**
