### PR TITLE
Bring make up to date

### PR DESCRIPTION
**Pull request by tjguk**
This PR includes all the changes made to the Makefile since make.py  was created. Except... for the translation logic which I need to decode from the bash command pipeline in translate.

I'd like to get this merged sooner than later so I can run the checks against other PRs

### CODE REVIEW

**Comment by ntoll** [comment]
I'll merge this now, since the checks (at time of writing, currently incomplete) don't touch this code.

Having said that, appveyor is a Windows environment, so I could update the .appveyor.yml file to use make instead of manually calling `win_installer.py`.

**Comment by ntoll** [comment]
Thanks for the contribution..! :-)

**Comment by ntoll** [comment]
Ouch...

```
./make.py:206: undefined name 'pygettext'
```

**Comment by tjguk** [comment]
Thanks, @ntoll. I wouldn't touch appveyor for now: although I've implemented the installer make targets they've hardly been given a thorough workout.

(Just say the error; I'll get back and fix that)

**Comment by ntoll** [comment]
Should that be `PYGETTEXT'..?

**Comment by tjguk** [comment]
Yes; I refactored this morning and didn't re-run make check on make.py!

**Comment by ntoll** [comment]
OK... I'll fix and push.

**Comment by tjguk** [comment]
Thanks; sorry...

**Comment by ntoll** [comment]
Done... no need to apologise! Thanks for these contributions!

If I had a pound for every time I forgot to run `make check` and broke the tests.... well, I could retire to full time Tuba playing... ;-)

**Pull request merged**
