### PR TITLE
Encodings

### PR DESCRIPTION
**Pull request by tjguk**
DO NOT MERGE

This PR includes the basic changes and test fixes to integrate with the Mu editor logic the encode/decode and line-endings functionality which was added by the now-merged #390.

So far the test changes I have made are simply to get the existing test suite passing. I have yet to add tests which exercise the interaction betwen the already-tested read/write functions and the already-tested editor load/save functionality.

Several of the tests I've changed I've refactored considerably, making use of common mocks etc. My reason for this was that, as a newcomer to the test suite, I was finding it difficult to separate the essentials of the test ("What's being tested here?") from the boilerplate test code needed to support the test. Since I had to change the test itself in the light of the new functionality, I had to be certain of what I was testing.

I believe that those tests I have changed are now easier to reason about and therefore to change or investigate. However, I'm conscious that this may not be an approach which is to everyone's taste. In addition, I've only changed those tests which were failing. This means that there is now a mix of styles within the test suite.

Examples of tests I've refactored include:

- test_editor_restore_session_invalid_mode
- test_save_no_path
- test_save_with_no_file_extension

I'd appreciate comments from the other developers before I go too much further down this road.

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Wow that's looking cool :clap: :clap: :clap:

**Comment by ntoll** [comment]
This pull request **introduces 1 alert** when merging d089d055ff10641334ae7726f535cd21bce7322f into 6121350e5261df15cd7542fa938c2e0aab6b4fc2 - [view on lgtm.com](https://lgtm.com/projects/g/mu-editor/mu/rev/pr-566a1cab87eef359fa89cf7f0c17420289de26d2)

**new alerts:**

* 1 for Unreachable code

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ntoll** [comment]
This pull request **introduces 1 alert** when merging be0dfa545d4ee32e055b9e3a49a0de11613176e2 into 6121350e5261df15cd7542fa938c2e0aab6b4fc2 - [view on lgtm.com](https://lgtm.com/projects/g/mu-editor/mu/rev/pr-2adc0c70dd8052b8cbab6c8413836127367e20c6)

**new alerts:**

* 1 for Unreachable code

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ntoll** [comment]
This pull request **introduces 1 alert** when merging 2ccff5f1feab3b110cb77adcd81d20d80397ba2d into 6121350e5261df15cd7542fa938c2e0aab6b4fc2 - [view on lgtm.com](https://lgtm.com/projects/g/mu-editor/mu/rev/pr-ea22bb624d9d6a43841e73cfd374e687fc51df8f)

**new alerts:**

* 1 for Use of the return value of a procedure

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ntoll** [comment]
Is this ready for review/merge..? (I'm excited about this landing...)

**Comment by tjguk** [comment]
Pending the outcomes of the CI checks running now, I think this PR is now a candidate for merging. All offline checks / tests pass. Beyond the points made previously about the test changes, the following questions are still worth considering:

* What to do when unpacking hex files (Currently: nothing; probably should do something)
* Does our [New] file become the single-line encoding cookie? (Currently: no; perhaps should be: yes)
* What do we put on the error dialog? (Currently: cf https://github.com/tjguk/mu/blob/6ef7c3ba202038b8abfae26c49cc8d1d82bac957/mu/logic.py#L616)

**Comment by tjguk** [comment]
Looks like mock.assert_called was only introduced in 3.6:

https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_called

I'll rework to use one of the other assertions.

**Comment by ntoll** [comment]
Hmm... I notice Travis is failing on 3,5.

**Comment by ntoll** [comment]
SNAP! :-P

**Comment by tjguk** [comment]
(I'll also sneak in the design notes which got lost in the transition from #371 to #390 / #391)

**Comment by ntoll** [comment]
This pull request **introduces 1 alert** when merging ea8442d67a3f990fd5f0c3bf4bc1748352519266 into 6121350e5261df15cd7542fa938c2e0aab6b4fc2 - [view on lgtm.com](https://lgtm.com/projects/g/mu-editor/mu/rev/pr-462e0ef21de4055166ec2ead6454a002ab5086d9)

**new alerts:**

* 1 for Use of the return value of a procedure

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by ntoll** [comment]
Hi @tjguk I'm going to merge this very soon. There's a code coverage niggle (a couple of lines in `_load` in logic.py are not exercised), some white-space formatting in the error explanation displayed to the user, and an alert from LGTM for returning the result of a "procedure" that never returns anything.

I'll fix these up and merge momentarily.

THANK YOU for all your work on this. :-)

**Comment by ntoll** [comment]
@tjguk have you forgotten to add an update to the `mu/interface/main.py` file..? I'm working my way through the code and trying things out and I'm getting all sorts of errors and crashes. E.g. new files don't have a `newline` associated with the tab object (by default) so cause a crash when you try to save them. When adding a tab, the function signature is wrong (we're calling with the `newline` but the `add_tab` function doesn't have that arg). These appear to be simple to fix, but I wonder if it all works for you but you've just not added the files with your changes to this PR.

**Comment by tjguk** [comment]
@ntoll I think what's happened is, on the 3rd rework, I ended up testing via tests rather than by actually running the program! And thus missed some slightly obvious tricks. I'm happy for you to to fixup / add tests or to throw it back in my direction and let me do the same.

**Comment by ntoll** [comment]
Absolutely, no problem. I'm just fixing things right now. :-)

**Comment by ntoll** [comment]
@tjguk quick question... I see the following when I re-load a file containing Chinese characters:

```
# -*- coding: utf-8-*-# Encoding cookie added by Mu Editor
????
```
When I can open the file in, say, vim and see:
```
# -*- coding: utf-8-*-# Encoding cookie added by Mu Editor
你吃了吗
```

Is there some setting on the EditorPane I need to enable to display the characters properly. When I first pasted them into the editor they displayed correctly.

**Comment by tjguk** [comment]
I don't understand why that should happen. I admit I only tested with European characters (£ signs etc) but there wasn't a problem. We're obviously decoding to Unicode which QScintilla should work with natively.

**Comment by ntoll** [comment]
OK... fixed it: http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciScintilla.html#a9071c0772ce576f60fce08395ce04274 ;-)

**Comment by tjguk** [comment]
Wow... I've clearly not actually run this code from the front-end! I've been so busy writing tests that I didn't recently check that you could actually load and save files. Sorry... Hopefully the tidy-up work isn't too much

**Comment by ntoll** [comment]
This is why we have code reviews and absolutely no problem at all! :-) Just doing some final checks before merging.

**Comment by ntoll** [comment]
OK... merged. Thanks for your efforts @tjguk :-)

**Comment by yonghuming** [comment]
```
# -*- coding:utf-8 -*-
# 你
print("你好")

```
could write chinese but could not print

**Comment by ntoll** [comment]
It works for me! Are you using the latest build of the installer..?

chinese_mu

**Pull request merged**
