### PR TITLE
Scintilla range namedtuple

### PR DESCRIPTION
**Pull request by tjguk**
We make use of Scintilla ranges to manage the highlights applied when text is highlighted. The Scintilla interface returns a tuple of from_line, from_offset, to_line, to_offset; the existing mu code manages them variously as those tuple components and as a dictionary keyed on (slight variants of) those field names.

This PR proposes to standardise on a class to handle Ranges where they occur. In the first instance, a namedtuple is used: it compares cleanly to the tuple objects returned by the Scintilla API while offering named-field access when it's needed.

It's possible that, in the future, a more elaborate class might be used which could, eg, convert between Scintilla's absolute document position and its line/offset values.

The branch also add a couple of tests to bring the coverage up to 100%

### CODE REVIEW

**Comment by ntoll** [comment]
PEP8 errors have broken the build.

Silent night, holy night,
All is calm, all is bright
Round yon pull request, code and build checks,
Wholly inadequate tests based on specs,
Sleep in heavenly PCs,
Sleep in heavenly PCs.

(Sorry, it just had to be done...)

:santa: :christmas_tree: :musical_note:

**Comment by tjguk** [comment]
Well Appveyor is giving a syntax error, which probably means I've used some Py3.5-specific syntax, since all the tests and checks pass here. And Travis just seems to have given up altogether.

**Comment by ntoll** [comment]
I see in Travis:

```
./mu/interface.py:65:80: E501 line too long (95 > 79 characters)
./mu/interface.py:66:80: E501 line too long (91 > 79 characters)
./mu/interface.py:67:80: E501 line too long (97 > 79 characters)
./mu/interface.py:358:21: E128 continuation line under-indented for visual indent
./mu/interface.py:474:80: E501 line too long (84 > 79 characters)
./mu/interface.py:475:80: E501 line too long (82 > 79 characters)
./mu/interface.py:65:80: E501 line too long (95 > 79 characters)
./mu/interface.py:66:80: E501 line too long (91 > 79 characters)
./mu/interface.py:67:80: E501 line too long (97 > 79 characters)
./mu/interface.py:358:21: E128 continuation line under-indented for visual indent
./mu/interface.py:474:80: E501 line too long (84 > 79 characters)
./mu/interface.py:475:80: E501 line too long (82 > 79 characters)
./mu/interface.py:476:80: E501 line too long (84 > 79 characters)
./mu/interface.py:484:33: E225 missing whitespace around operator
./mu/interface.py:523:80: E501 line too long (84 > 79 characters)
./mu/interface.py:476:80: E501 line too long (84 > 79 characters)
./mu/interface.py:484:33: E225 missing whitespace around operator
./mu/interface.py:523:80: E501 line too long (84 > 79 characters)
```

**Comment by tjguk** [comment]
*Cough* it helps if you actually commit stuff before you push!

**Comment by tjguk** [comment]
Ok; I seem to have a 3.4 environment working on Windows now (was on 3.5 because PyQt5 is pip-installable there). Ignore this PR until I've ironed out the 3.5/3.4 differences which are causing the CI to fail.

**Comment by tjguk** [comment]
(although, to save me effort, feel free to chime in if you think it's taking things in the wrong direction anyway)

**Comment by tjguk** [comment]
I'm going to withdraw this PR. I still think it's a good idea but, pre-3.5, the gains aren't so great as I'd hoped. More generally I might push some time for our own subclass of the QsciQScintilla control which could simplify some of the code in the mu.interface module but for now I think the benefit of this PR to the codebase is outweighed by the churn it creates.

**Pull request closed without merging**
