### PR TITLE
setup.py: Upgrade dependencies to fix AppVeyor and Travis CI macOS

### PR DESCRIPTION
**Pull request by cclauss**
A subset of #957 that gets the CI green again.

### CODE REVIEW

**Comment by tmontes** [comment]
@cclauss,

Thanks for the PR, this relates to #893 so leaving this note here to link things around. :)
There's an outstanding decision around "locking" vs "latching" vs "nothing" with regards to dependency versions there which I feel needs consideration and decision.

Nevertheless, I feel your PR should be merged. There are a few things I don't understand though:

* Why are you changing `flake8`'s and `black`'s latching?
* More importantly, why is `python-datetutil` being explicitly added and locked to that specific version?

Standing by.

**Comment by cclauss** [comment]
The first commit was called __setup.py: python-dateutil==2.8.0 to fix appVeyor__.

On flake8 and black, I saw that we were passing tests with the latest and greatest so I "latched them up".  In general, I tend to pin (lock) runtime dependencies but let testing tools (pytest, flake8, black) use the latest and greatest so that as they add more tests, we test our code more.  Definitely a matter of personal taste.

**Comment by tmontes** [comment]
> The first commit was called **setup.py: python-dateutil==2.8.0 to fix appVeyor**. It will fail without pinning.

You mislead me here: locking `python-dateutil` addresses the macOS Travis job failure, in the packaging stage, not AppVeyor (that failure is explained in #958 and fixed by #961).

The unfortunate motive for that is that, on one hand, Mu depends on `qtconsole==4.4.3`:
* ...that depends on `jupyter-client>=4.1`...
* ...that depends on `python-dateutil>=2.1`.
* This leads `pip` to select `python-dateutil==2.8.1` for installation.

But then, on the other hand, Mu also depends on `briefcase==0.2.9` for macOS packaging:
* ...that depends on `boto3>=1.4.4`...
* ...that depends on `botocore<1.14.0,>=1.13.28`...
* ...that very recently, [in this commit](https://github.com/boto/botocore/commit/e87e7a745fd972815b235a9ee685232745aa94f9), updated its `python-dateutil` dependency to `python-dateutil<2.8.1,>=2.1`.
* At this stage `pip` emits a warning as it was the case [in this build line](https://travis-ci.org/mu-editor/mu/jobs/618370793#L665), that I quote here:
```
ERROR: botocore 1.13.28 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7",
but you'll have python-dateutil 2.8.1 which is incompatible.
```

PS: Yes, `pip` should be more clever about it. But it isn't. Yet. The PSF is promoting such improvement, which is a good thing. :)

With this in mind, and without diving into the larger discussion of #893 (what to lock, what to latch, etc), I would suggest:

* Bring the `python-dateutil==2.8.0` line further up, maybe right before the `qtconsole` one.
* Precede it with a comment explaining the motive for such apparently out of context lock.

What do you say? Would you improve it in some other way? :)

> On flake8 and black, I saw that we were passing tests with the latest and greatest so I "latched them up". In general, I tend to pin (lock) runtime dependencies but let testing tools (pytest, flake8, black) use the latest and greatest so that as they add more tests, we test our code more. Definitely a matter of personal taste.

That sounds perfectly reasonable. Ultimately I do not think it comes down to a matter of personal taste though. :) I'll be glad to discuss the topic, and coming up with a strategy and policy in this regard that better serves Mu, its contributors and, in the end, all Mu users. #893 is waiting for us there! :)

**Comment by ntoll** [comment]
Hi folks, I intend to deep dive into all things packaging related this week, including ensuring CI things are green -- thank you so much for the work done so far. I'll make sure I reference this ticket as I make progress (or not). ;-)

**Comment by dybber** [comment]
The version conflict issues surrounding `python-dateutil` reappeared today, when looking at this again in #1065,  but with another package `docutils`, that also is brought in by briefcase 0.2.9 through its `boto3` dependency. The longterm solution will be to upgrade to briefcase 0.3.0, which doesn't have the dependency on boto3. I've made an issue #1066 on doing such an upgrade.

**Comment by tjguk** [comment]
Thanks for the work here, @cclauss . I've just merged #1065 which *looks* as if it supersedes your patch here. Could you just confirm and either close (with our many thanks for taking the trouble) or let me know if there's still something which needs merging? Thanks

**Comment by dybber** [comment]
We're getting warnings on pycodestyle and pyflakes, and flake8 brings them in, so it could be that we should also apply that change to master (i.e. remove the explicit dependencies on pycodestyle and pyflakes), however, the explicit python-dateutil pinning doesn't seem to be necessary anymore.

**Comment by tjguk** [comment]
Ok; I've given it a quick test-run locally and I don't see any immediate issues. Let's merge it now and watch the builds

**Comment by dybber** [comment]
I still don’t see the need for the python-dateutil dependency.

**Comment by tjguk** [comment]
If it's not causing a problem building, I'll pull it out of my current dev branch and check that we're still ok...

**Pull request merged**
