### PR TITLE
Prep babel translations - take 2

### PR DESCRIPTION
**Pull request by xbecas**
@tmontes et al.

Second attempt at preparing i18n files with Babel. Following Tiago's instructions I prepared all available languages but `pt_PT`, as I am working on it.

I fixed all timezones' issues with `+CEST` and `+JST`, replacing the textual codes with the equivalent 4-digits numerical ones, namely and respectively `+0200` and `+0900`.

Looking forward to getting your review and notes.
KR

### CODE REVIEW

**Comment by ntoll** [comment]
So, over the weekend, someone emailed me to point out a typo in one of the English strings. Let me address that, and then we can re-generate these files (without the typo in them) again..? (So sorry about this - I only checked my email this morning).

**Comment by ntoll** [comment]
OK... I've just updated `master` to correct the typo. You should be good to go to recreate the translation strings. Once revised, I'll merge and write up a blog post to get folks interested in updating the translations..! :wink:

**Comment by ntoll** [comment]
Hmm... I don't see the new string "compatible" (found in `logic.py`) in the updated files. Did you rebase your branch before redoing the files..?

To rebase:

```
git checkout master
git pull origin master
git checkout prep-babel-translations
git rebase master
```

Then re-run. Any problems just shout..! :tada:

**Comment by ntoll** [comment]
You'll know it works because you'll see a new string `" compatible"` from the logic.py file to be translated. :+1:

**Comment by tmontes** [comment]
Great @xbecas, thanks for keeping at it. Merging! :)

**Comment by xbecas** [comment]
Thank you @tmontes, @ntoll et al. for assisting me in my first merged contribution. A small step for Mu-Editor, a giant step for me! 🎉

**Pull request merged**
