### PR TITLE
Improved Chinese translation.

### PR DESCRIPTION
**Pull request by JohnGuan**
The old translation files are hard to understand. I recreated the translation file and re-translated it. This is a well-prepared complete Chinese translation, the next step will be to start translating the module's docstring.

### CODE REVIEW

**Comment by ntoll** [comment]
Hi @JohnGuan,

Many thanks for your contribution. I'd like to introduce you to @yonghuming who worked on the original Chinese translation. It's good to collaborate, cooperate and discuss such changes so I'll merge this in a few days time (it'll get into the next release) so people have a chance to discuss.

Best wishes,

N.

**Comment by JohnGuan** [comment]
Hi @ntoll ,

Thank you for your reply. I am teaching Python, MicroPython, MicroBit, Raspberry Pi and other related courses in China. This is a great project. I will continue to support the development and Chinese localization of the mu project, not just the translation of the software interface. If there are other places that need support, please let me know.

Best wishs,

John Guan

**Comment by ntoll** [comment]
@JohnGuan OK... merged for pending 1.0.1 release. Thank you for your contribution. :-)

**Comment by yonghuming** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        i am here
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                964683112
                            
                    
                        
                            
                                    964683112@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 9/7/2018 18:52，Nicholas Tollervey<notifications@github.com> wrote： 


Hi @JohnGuan,
Many thanks for your contribution. I'd like to introduce you to @yonghuming who worked on the original Chinese translation. It's good to collaborate, cooperate and discuss such changes so I'll merge this in a few days time (it'll get into the next release) so people have a chance to discuss.
Best wishes,
N.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yonghuming** [comment]
@JohnGuan good work，

**Comment by JohnGuan** [comment]
@yonghuming thank you，谢谢

**Pull request merged**
