### PR TITLE
Locale SK

### PR DESCRIPTION
**Pull request by ricco386**
We have translated Mu editor to the Slovak language.

### CODE REVIEW

**Comment by ntoll** [comment]
@ricco386 oh man, you just made my evening! ;-)

Can we hold off merging this. I'm doing a block of work for the next 2-3 weeks that will probably add some more strings to be translated. I'll give you a kick and let you know the specific additions closer to the time. Is that OK?

And THANK YOU!!!! :-)

**Comment by ricco386** [comment]
@ntoll sure no problem, take your time... In 3 weeks my responses might be a little bit slower as we will be fairly close to the PyCon SK, but afterward, I'll be all in as we want to start a pilot project with micro:bits in a couple of schools...

**Comment by ntoll** [comment]
Great stuff. Please let me know if there's anything I can do to help! :-) (And best of luck with PyCon SK)

**Comment by ntoll** [comment]
Hi @ricco386 -- the UI is  complete. Please check and revise. Would love to have your translation in the release candidate. :-)

**Comment by ntoll** [comment]
Hi @ricco386, the RC will be out this afternoon... If you're quick I could squeeze this into 1.0 final. :-)

Many thanks for all your help with this.

**Comment by carlosperate** [comment]
Hi @ricco386, first of all thank you so much for the PR! Sorry it's taken so long to look into this again, after the v1.0 release the work on v1.1.0 included significant changes which affected a lot of the translatable string we didn't really update the translations until the project was ready.

Now that we are close to the v1.1 final release the strings are frozen, the translation framework updated, and we are ready for translations again 🎉 

If you are still happy/available to help us there is more information here, thanks a lot! 
- https://github.com/mu-editor/mu/discussions/1931

**Comment by carlosperate** [comment]
As we have included a Slovak translation via https://github.com/mu-editor/mu/pull/1978 we can close this as completed via the other PR.

Thank you again for your contribution!

**Pull request closed without merging**
