### PR TITLE
Add a mode for the MicroPython Pyboard

### PR DESCRIPTION
**Pull request by kyoungmeyer**
Add a mode for the MicroPython PyBoard. The API includes most of the 'pyb' module, found in the documentation located [here](https://docs.micropython.org/en/latest/pyboard/library/pyb.html). Other PyBoard specific modules have not been added at this time. The Adafruit mode was used as a base to this mode, due to the similarities.

### CODE REVIEW

**Comment by ntoll** [comment]
Oooh... this is great work. Thank you @kyoungmeyer..! The upcoming 1.0.1 point release is just for bug fixes (no new features). However, this should go in the 1.1 release scheduled for later this autumn.

**Comment by ntoll** [comment]
This pull request **introduces 1 alert** when merging f2539852c3593ae5f83ed3d2cf887df02e92dabd into acf9cb00893d776b5fe52d1c8c4fb9ab04c48503 - [view on LGTM.com](https://lgtm.com/projects/g/mu-editor/mu/rev/pr-453c8d0648367deeceb9213a6973b4f58ddf32a6)

**new alerts:**

* 1 for Duplicate key in dict literal

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by kyoungmeyer** [comment]
Looks like Travis CI build failed due to issue #909

**Comment by dybber** [comment]
Hi @kyoungmeyer, sorry for the big delay in coming to this. I've just ordered a pyboard to be able to test this mode and do a review, so hopefully we'll be able to get Pyboard mode into Mu soon. 

We've recently made some changes to how device detection works in Mu, so you might want to look at how to update your PR to adhere to that new interface, if you have the time, otherwise, I will look at it when I receive the pyboard.

**Comment by dybber** [comment]
I still haven't received my pyboard, it would still be helpful, if you would rebase your branch on top of the current master, to get it to adhere to the new interface, e.g. how you specify the list of supported devices has changed.

**Comment by southqaw** [comment]
@dybber, no problem at all. Sorry for the delayed response, I somehow had notifications turned off on this request.

I'll get the branch rebased to the current master as soon as I can.

**Comment by kyoungmeyer** [comment]
@dybber, no problem at all. Sorry for the delayed response, I somehow had notifications turned off on this request.

I'll get the branch rebased to the current master as soon as I can.

**Comment by dybber** [comment]
Thanks. I have received the Pyboard, however, I'm quite busy at my job the coming two weeks, but I will try to find time to look at your PR soon!

**Comment by dybber** [comment]
Thanks @kyoungmeyer!

**Pull request merged**
