### PR TITLE
More styling work

### PR DESCRIPTION
**Pull request by ZanderBrown**
This has grown a bit

On macOS/Linux/Windows our scrollbars use a Qt fallback which looks *interesting* and is almost invisible in the contrast theme. Similarly masOS/Windows/Some Linux fallback to a grey on grey 9xish design.

So visually this PR styles the scrollbar & dialog buttons and adds some borders to text areas in the admin dialog

Some pictures!

mubuttons
Haven't included hover states here because reliably screenshotting them was an issue

muscroll

Whole admin dialog for comparison
screenshot from 2018-07-09 17-51-10
screenshot from 2018-07-09 17-51-21
screenshot from 2018-07-09 17-51-41

Codewise this sets the stylesheet globally instead of per window/widget. Don't have any metrics but in theory this should be more efficient as it avoids parsing the theme multiple times.

This reduces the need to pass the theme around all the time and ensures everything is themed (See unsaved work dialog)

Obviously a lot of this is up for discussion and #530 could help simplify many areas of theme handling

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Also included: Mode selector preselects the current mode reducing the changes of accidental switches

**Comment by ntoll** [comment]
Aha... so you've just missed beta.17, but should be able to make RC. :-)

**Comment by ZanderBrown** [comment]
Hoped to get thing sent in by 4 but life got the better of me

**Comment by ntoll** [comment]
The images look good too... I'll get to this tomorrow (currently writing a blog post about beta.17 release announcement).

**Comment by ntoll** [comment]
Heh... I hoped to have beta 17 out last Wednesday... ;-)

**Comment by ntoll** [comment]
OK... took a quick look and merged it. Nice work! Thanks.

**Pull request merged**
