### PR TITLE
Fixes Mu-Terminal utf-8 encoding. Fixes #759

### LINKED ISSUE #759: wrong Circuitpython Umlaute äöüß
The german Circuitpython-translations aren't displayed properly in the MU-Terminal. 
The encoding is wrong (not UTF-8)
`ZurÃ¼ckverfolgung (jÃ¼ngste Aufforderung zuletzt)` should be `Zurückverfolgung (jüngste Aufforderung zuletzt)`

It is a MU problem because the terminal-program _screen_ shows it correct.

https://github.com/adafruit/circuitpython/issues/1112#issuecomment-460053098

### PR DESCRIPTION
**Pull request by k0d**
The Mu-Terminal doesn't display utf-8 characters correctly. This PR fixes that issue by decoding to UTF-8 first, then checking for VT-100 sequences etc.

I've tested this against the Swedish translation of CircuitPython on a Serpente board.

### CODE REVIEW

**Comment by dybber** [comment]
Great! I just want to mention, that I've almost completely reworked the VT100-handling, to improve cursor movement and text selection in the terminal in this pull request: https://github.com/mu-editor/mu/pull/1026 (not merged yet). I think it would be nice to merge these two, and it would probably be easiest to redo your changes on top of that other pull request. If you want to, I can also take a look at it.

Best regards,
Martin

**Comment by k0d** [comment]
@dybber I'll take a look at it. Though my initial thoughts would be that my changes are so small that it'd be better to have it as a separate pull request.

**Comment by dybber** [comment]
Did you take a look at it? Otherwise I don't mind looking at it.

**Comment by k0d** [comment]
@dybber I still feel that it's best to have this as a smaller separate PR. I'd kind of forgotten about it as it was quite a few days ago.

**Comment by carlosperate** [comment]
Thank you for your PR @k0d. This implementation works more efficiently than https://github.com/mu-editor/mu/pull/817, but both PRs now don't deal well with UTF-8 characters broken down between multiple `process_bytes()` calls, as the serial input can be broken down in smaller blocks we can have incomplete muti-byte characters, so we need to check the start and end of each data array to look out for these.

I've been looking into this a couple of weeks ago, but didn't quite finished it up, so I still need to push my findings. Please let me know if this is something you would like to continue working on.

**Comment by dybber** [comment]
Hi @k0d, I've integrated your changes with mine, and @carlosperate made some performance tests over at #797. My branch is now merged with master and I will thus close this PR. Thank you for the contribution!

**Pull request closed without merging**
