### PR TITLE
Window sizing changes

### PR DESCRIPTION
**Pull request by tmontes**
This PR implements the proposed changes in #757:
* Minimum Mu window size now set to half the screen width and height.
* Mu window size and position is now saved in the session and restored on the next launch.

For context, please refer to the issue. Thanks. :-)

### CODE REVIEW

**Comment by tmontes** [comment]
UPDATE NOTE:
* Resolved merge conflicts with `master`.
* In particular, commit c504df7e56cf2226f8f373b1a6c3753c17979fac, which keeps a hard-coded approach at the minimum window size: this is not a technical conflict but a conceptual/usability one, instead. Probably needs further discussion. :)

**Comment by ntoll** [comment]
Great work here... this is another niggle of mine that you've managed to fix. ;-) Thank you @tmontes

**Comment by tmontes** [comment]
> Great work here... this is another niggle of mine that you've managed to fix. ;-) Thank you @tmontes

Thank you for reviewing and merging. In this area what I feel is pending, with very little effort, is tuning the window size thresholds for button resizing. The default window/button size on the mac truncates the Quit button on the right. Maybe we can fix that sometime next week, I say. :)

**Comment by ntoll** [comment]
I was just thinking the same thing. :-)

**Pull request merged**
