### PR TITLE
Pixel kit

### PR DESCRIPTION
**Pull request by murilopolese**
Hello!

My name is Murilo and I work for a company called [Kano](https://kano.me). There, I'm currently working on converting one of our products ([Pixel Kit](https://kano.me/store/uk/products/pixel-kit)) to be a MicroPython enabled device for less "beginner" audiences. As we love Mu Editor we would really like to be able to use it as the official code editor for this purpose. This would mean a lot for us and I guess for Mu as well as we would push it to our significantly large user base (including in our KanoOS and everything).

It took me a while to write this PR as I'm no Python developer and I wanted to keep the code standards as high as I could to honor the pleasure that was reading Mu's code for the first time. So I guess this is more a request for feedback than to merge the code. It's also missing a few bits* but I believe that would be nice to get feedback before I finish everything :)

So this is what this PR aims to:

- Create a Kano Pixel Kit Mode to allow users programming their Pixel Kits in MicroPython
- Flash their Pixel Kits with MicroPython and back to Kano Code firmware (the UI for this second part is not finished yet)
- Access the MicroPython REPL over USB Serial
- Run and interrupt code on the board
- Transfer files between MicroPython filesystem and your local machine

Missing bits:

- Moar tests!!
- Change the label on the File Manager from "micro:bit" to "Pixel Kit"
- Mu stops responding when opening the REPL after flashing the device without restarting it
- Maybe extracting a few classes from BBC:microbit mode to avoid code duplication, etc

Here are some [screenshots](https://imgur.com/a/yLlTIkZ) of how the mode looks like!

Looking forward to hear your suggestions, recommendations, feedback, ideas, etc!

### CODE REVIEW

**Comment by ntoll** [comment]
This pull request **introduces 1 alert** when merging 2ace50da26a0bd557af0b73de5772d022b1cebe9 into 0afdb3869aca6a6102d226fbd7ed39f2e0387726 - [view on LGTM.com](https://lgtm.com/projects/g/mu-editor/mu/rev/pr-677b82f5e67c9ec83361d6c25f5aa6eafd24bd0a)

**new alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by murilopolese** [comment]
I'm still getting this which I am not sure how to solve/what's the problem:

```
./tests/modes/test_pixelkit.py:43:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:167:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:168:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:333:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:334:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:335:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:366:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:367:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:368:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:396:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:407:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:418:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:419:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:429:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:478:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:479:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:480:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:501:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:502:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:503:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:523:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:524:10: E127 continuation line over-indented for visual indent
./tests/modes/test_pixelkit.py:525:10: E127 continuation line over-indented for visual indent
```

**Comment by ZanderBrown** [comment]
The code is indented too far, try removing some spaces

**Comment by ntoll** [comment]
Hi @murilopolese,

Great stuff... I'm in meetings all day today, but will look into this tomorrow and provide feedback, especially when it comes to the errors/warnings you're seeing (these are our code quality checks complaining about linter-y and layout type things).

;-)

Thanks,

N.

**Comment by murilopolese** [comment]
Hey, @ZanderBrown! I tried many different ways to indent it and it seems that adding that extra "tab" was the way to make the checks pass :s If I indented it visually would fail, if I let only one "tab" failed, when I added 2 "tabs" worked even that is not what I understood from the [E127](https://lintlyci.github.io/Flake8Rules/rules/E127.html). But again, I am sure I'm doing some silly mistake and happy to fix it when I learn what's going on!

Thanks big time, @ntoll! Such a rookie mistake, I submitted the PR without running `make check`, shame on me!

**Comment by ntoll** [comment]
OK... 1.1 milestone added... so it's going in! :-)

**Comment by ZanderBrown** [comment]
@murilopolese was playing around with this but occasionally Mu crashes when using the REPL

```
panes.py, line 237, in process_bytes
    i += m.end() - 1
AttributeError: 'NoneType' object has no attribute 'end'
```

**Comment by murilopolese** [comment]
@ZanderBrown indeed! I haven't really touched `panes.py` and I'm basically copying and pasting the REPL code from the microbit mode so this bug is still a bit of a mystery for me. I must confess I haven't spent as much time as I wanted on it. You can consistently reproduce a similar bug (or the same, I don't know) by flashing the board and trying to open the REPL without reconnecting the USB.

I have a separated branch where I merged the latest `master` and this doesn't appear to happen anymore... https://github.com/murilopolese/mu/tree/pixel-kit-merged

Do you have an idea what it could be? I'm working on it as we speak.

**Comment by ZanderBrown** [comment]
Looks like some kind of malformed control sequence is being sent by the Pixel Kit

Between your branches

https://github.com/murilopolese/mu/blob/99c95036e939fa0d5f931d99a7338c5d268b141f/mu/interface/panes.py#L231-L238

has become

https://github.com/murilopolese/mu/blob/22068d68f2fe9b4c257efc49b96e82e7185b4ec7/mu/interface/panes.py#L231-L240

So at least Mu shouldn't crash anymore

**Comment by murilopolese** [comment]
Hmmm... That sounds right. I believe while flashing with the `esptool` there might be some gibberish coming from the serial. I do experience it when I'm using `screen` to connect to it.

@ZanderBrown, on a more practical side: Would you recommend me to rebase/merge this branch with master now or leave it for an eventual merge if this PR gets through?

**Comment by murilopolese** [comment]
It's with a heavy heart that I come here to close this pull request. I don't think the Pixel Kit mode makes sense anymore and I'd like to vouch for including [this mode](https://github.com/mu-editor/mu/pull/676) instead that will work not only with the ESP32 inside the Pixel Kit but most other ESP8266 and ESP32 boards. I have tested at home and I hope I can contribute to it instead :)

**Comment by ntoll** [comment]
Oh what could have been... but having said that, such activity always presents an opportunity to learn (and hopefully reapply our new-found knowledge). Onwards and upwards... :+1:

**Pull request closed without merging**
