### PR TITLE
Add japanese translate file.

### PR DESCRIPTION
**Pull request by MinoruInachi**
I have translated mu.po for Japanese language.

### CODE REVIEW

**Comment by ntoll** [comment]
Hi @MinoruInachi 

Apologies for the tardy response time on my part... this is a volunteer run project and sometimes things take time.

I'll leave this PR open for the time being since we're still making slight changes to the UI that could affect the translation strings. I'll add such details to this PR (so you have a chance to check and update) once the UI work for 1.0 is settled down.

Once again, thank you for your contribution.

N.

**Comment by ntoll** [comment]
Hi @MinoruInachi the UI is now complete so please check and revise. Thank you for your contribution. I'd love to get this into the release candidate at the end of the week! ;-)

**Comment by MinoruInachi** [comment]
@ntoll Japanese Translation updated.

**Comment by ntoll** [comment]
Apologies... also this change too (this will be the last one):

https://github.com/mu-editor/mu/blob/master/mu/interface/main.py#L353

**Comment by MinoruInachi** [comment]
@ntoll Japanese Translation updated for latest 1.0 candidate.

**Comment by ntoll** [comment]
Merged! Hurrah. Many many thanks @MinoruInachi -- it'll be in the release candidate. :-)

**Pull request merged**
