### PR TITLE
Issue209 left shift unselects regex

### PR DESCRIPTION
**Pull request by tjguk**
All tests are now passing, including a new test for the specific situation which caused this issue. I've moved further rework into issue #212

### CODE REVIEW

**Comment by ntoll** [comment]
Build is failing due to PEP8 errors. Please use `make check`. ;-)

**Comment by tjguk** [comment]
Middle of... (can't [easily] use make check because Windows!)

**Comment by ntoll** [comment]
Ah. I'm all ears to make Mu development Windows friendly. Any suggestions..?

**Comment by carlosperate** [comment]
This is something that's been on my mind for a while, we could easily replicate the make file functionality with a python script. That would also make https://github.com/mu-editor/mu/pull/203 obsolete, although @ntoll, could you merge https://github.com/mu-editor/mu/pull/203 first to make sure we are running the tests on windows more "natively"?

**Pull request merged**
