### PR TITLE
Add environmental markers to setup.py and requirements.txt

### PR DESCRIPTION
**Pull request by carlosperate**
From the discussion in https://github.com/mu-editor/mu/issues/671.

This also removes the need to have a separate requirements_pi.txt.
If accepted we also need to update this page as well to change the requirements.txt mention: https://mu.readthedocs.io/en/latest/setup.html

I've tested `pip install -e .` and `pip install -r requirements.txt` in macOS and Raspberry Pi.
I've also created a wheel in macOS, transferred it to raspberry pi and that works as well.

### CODE REVIEW

**Comment by carlosperate** [comment]
The current travis failure is due to an issue in briefcase: https://github.com/pybee/briefcase/pull/169

**Comment by carlosperate** [comment]
Briefcase has been updated and the CI passes.

**Comment by bennuttall** [comment]
:+1:

**Comment by ntoll** [comment]
OK... so regarding docs. The "blessed" way to install Mu on a Raspberry Pi is via the OS package and NOT via pip. I'm just updating the dev docs via this branch to highlight this problem, although the instructions found therein should still just work (since step 1 is to install the PyQt dependencies via ``apt-get``).

**Comment by carlosperate** [comment]
Great, thanks Nicholas! And thanks for updating the docs as well.

About what I mentioned in my last message in https://github.com/mu-editor/mu/issues/669#issuecomment-464752603 about adding a check on import to detect missing PyQt5 dependencies. Taking a pragmatic look, I agree that we should leave that as it is right now as the docs do have all the installation methods. If we start getting users hitting the same error via pip install on the Raspberry Pi we can then reconsider, but until then no need to guess, as alpha/beta testing we'll let us know.

**Comment by ntoll** [comment]
@carlosperate exactly... alpha/beta testing will highlight how visible this `pip` related problem may be for users on Raspberry Pi.

**Pull request merged**
