### PR TITLE
Allow a user to change manually change their locale via a new tab in the admin dialog.

### PR DESCRIPTION
**Pull request by ntoll**
This "spike" does exactly what it says on the tin. Once folks are happy with the approach I'll "solidify" the code with better and more specific test coverage.

It looks like this:

mu_select_translate

Feedback welcome.

### CODE REVIEW

**Comment by carlosperate** [comment]
Awesome!

Would a unicode emoji work in the settings tab? If Mu is configured in a language the user doesn't understand a globe icon (or flag/s?) usually helps identify the language menu.

**Comment by ntoll** [comment]
Hmm.... that's a great idea and I've just tried it, but the emoji looks very (too) small. I've tried, 🌍 💬 🗣️ and 🔤 and none of them look particularly good (IMHO).

**Comment by carlosperate** [comment]
Right, I guess the text in the tab is not very large.
Maybe @ZanderBrown knows how we could enlarge a unicode or svg emoji in a tab?

**Comment by ntoll** [comment]
Tēnā koe. :slightly_smiling_face: :new_zealand: :rocket: 

Of course. We even have docs (that need revising) that explain how to do this: https://mu.readthedocs.io/en/latest/translations.html

**Comment by ntoll** [comment]
And to be clear... we'd love a Māori translation of the UI @was-dtech - if you're offering... :+1:

**Comment by was-dtech** [comment]
Tēnā koe 😀   Will get onto it this weekend.  May need some help re the technical side of things.

**Pull request merged**
