### PR TITLE
Fix issue #595 - race condition, where a tab sometimes was renamed to name of other tab

### PR DESCRIPTION
**Pull request by dybber**
See description of the fix over in the bug report: https://github.com/mu-editor/mu/issues/595#issuecomment-642970812

### CODE REVIEW

**Comment by dybber** [comment]
Oh, forgot to look at the test cases, will update them tomorrow.

**Comment by tjguk** [comment]
Thanks @dybber; if you can get a test case in there I'm happy to merge this

**Comment by dybber** [comment]
Fixed the failing testcase.

**Comment by tjguk** [comment]
Thanks @dybber especially for the easily-reproduced test case

**Pull request merged**
