### PR TITLE
Attempt at fixing #921 through some changes to HiDPI settings

### PR DESCRIPTION
**Pull request by dybber**
This is an attempts at fixing the issue with HiDPI scaling on Windows 10 as mentioned in #921. I've not been able to test that this fixes the issues on Windows, as I'm on a Mac. I'm thus looking for someone who can test it.

### CODE REVIEW

**Comment by dybber** [comment]
Relevant part of the documentation: https://doc.qt.io/qt-5/highdpi.html

**Comment by carlosperate** [comment]
Was your branch from the latest commit in master?
Oddly enough this seems to have affected the Appveyor build and all the Linux and macOS travis builds (only macOs is expected to fail due to https://github.com/mu-editor/mu/issues/1155).

**Comment by dybber** [comment]
Yes, on top of master (this commit is previous commit https://github.com/dybber/mu/commit/3083c7736ecea168d3f3e308017bb8cb05b1ade7 )

**Comment by dybber** [comment]
Seems like it's just some tests that needs to be updated.

**Comment by dybber** [comment]
That was easy, but still getting errors on the new "QT_QPA_PLATFORM=offscreen" target, as the `Qt.AA_EnableHighDpiScaling` option doesn't seem to exist. @carlosperate, can you explain what that target is testing?

**Comment by carlosperate** [comment]
That's testing  the build in the Arm64 architecture for things like the Raspberry Pi, Chromebooks and Arm laptops.
If that doesn't exist in that Travis build environment then it's likely it won't exist in the Raspberry Pi either. Do you have one handy to test in that platform?

**Comment by dybber** [comment]
It would be pretty involved for me to set it up and test on a Raspberry Pi. My thought would be to change it to:

```python
os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
if hasattr(Qt, "AA_EnableHighDpiScaling"):
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps)
```

**Comment by carlosperate** [comment]
I won't be able to try it this weekend, but early next week I can give this a go in a Raspberry Pi

**Comment by dybber** [comment]
This seems to solve it for Surface Pro, as just confirmed in #921. However, I will wait merging this until you've had time to test it on Raspberry Pi, @carlosperate

**Review by carlosperate — APPROVED** [review]
Thanks Martin!

I was finally able to test on Raspberry Pi and works well. 👍 

I also tested on Windows on a macbook with a HiDPI built-in screen and a 4k external monitor and can confirm it fixes the issue there as well.

I've also tested this in an Ubuntu 20.04 VM with a 4k monitor with native resolution enabled in the VM (otherwise the VM software might do its own scaling) and with scaling enabled in the Ubuntu settings, and I can confirm this was also a problem there that is fixed with this PR. 🎉 

Interestingly macOS (I'm currently on Mojave) didn't have this problem. Nevertheless I can confirm Mu looks the same in my 4k display (with scaling enabled) with and without this PR.

**Comment by dybber** [comment]
Great, thanks for testing on all those platforms, Carlos!

**Pull request merged**
