### PR TITLE
Alternative cleaner approach to #685

### PR DESCRIPTION
**Pull request by tim-mccurrach**
Addresses the same issues as #685 (#707 ,#706 etc.) but does it in a much cleaner fashion.

The whole problem of having to deal with split utf-8 strings (issue #674 ), or other sequences such as `\r\n` (issue #683 ) can be avoided completely if we read the data line by line rather than in 256 byte chunks. This turned out to be significantly slower for actually printing something like a for loop, so I opted for reading a 256 byte chunk, and then some more up until the end of the current line. This makes the solution a lot shorter and simpler, and the code-base more accessible for beginners.

Since it relies on new-line characters, mu would still freeze in the following situation:
```
while True:
    print('Hello', end='')
```
However, I’m struggling to think of a situation where this could happen by accident. I think any beginner who is advanced enough to think about using the `end` keyword argument, would also be advanced enough to identify an infinite while loop, and understand what will likely happen. So whilst it doesn't cover every single case, might be a better solution than #685 . Simple is better than complex?

### CODE REVIEW

**Comment by tjguk** [comment]
Well I can confirm that it solves the problem where the output pane of a program is truncated short. The problem showed up in a session today when we were displaying a long list of words. Without the fix, the output stopped after a few hundred characters; with the fix -- after a delay -- all 360,000+ words were apparently displayed!

**Comment by tjguk** [comment]
Thanks @tim-mccurrach. From my point of view, this really isn't a showstopper. It's the common experience that outputting a large amount of text will tend to delay things, and this certainly wasn't an unconscionable delay -- just a few seconds.

(Of course if you can come up with something better, that would be good too!)

**Comment by ntoll** [comment]
Hi.

Thank you for your contribution and apologies for taking so long to respond.

I think I have a single line fix for this which fixes all the related issues and I've stuck it into #723 which I'll merge immediately so it'll get into the 1.0.2 point release.

Thanks, once again for all the work that went into this.

**Comment by tim-mccurrach** [comment]
👍  glad to. Learnt a lot doing so :)

**Pull request closed without merging**
