### PR TITLE
WIP: Even more CSS work

### PR DESCRIPTION
**Pull request by ZanderBrown**
Probably won't be done for 1.0

* [x] macOS tabs aligned left
* [x] Avoid titlebar like panel headings on macOS
* [ ] Enhance inspector appearence

### CODE REVIEW

**Comment by ntoll** [comment]
Oooh... thanks for this. Please do let me know when it's finished and ready for review.

**Comment by ZanderBrown** [comment]
Think I'm starting to go a little mad looking at 3-way diffs in Meld to check they are all in sync

If someone with access to a mac could check what it looks like that would be great!
screenshot from 2018-07-15 22-32-27

Have we had any feedback on the contrast theme?

**Comment by ntoll** [comment]
I'll be checking this later today.

When you say "Enhance inspector appearance" I notice you've done much of that already. What's left to do..? Can I merge this (really useful) work..?

**Comment by ZanderBrown** [comment]
Sure it's mergable had hoped to cleanup the header alignment but that can happen later/not a all

**Comment by carlosperate** [comment]
@ZanderBrown Does this help?

image

**Comment by ntoll** [comment]
@ZanderBrown @carlosperate it LGTM and the changes are something that I'd hope to have in 1.0 so I'll check / merge right now. :-)

**Comment by ZanderBrown** [comment]
Yes!

Looks like it's working but i'm slightly concered the far left tab has the close button on the left not the right

**Comment by carlosperate** [comment]
Oh yes, didn't even noticed!
In current master branch all tab close buttons are on the left (I assume to follow the mac window pattern).

**Comment by ntoll** [comment]
WRT the debug inspector... looks great! I think I've found a "niggle" (see photo below).

This isn't a show stopper, but the "whitespace" background when highlighted is still blue rather than grey.

inspector_blue

**Comment by ntoll** [comment]
This whitespace/blue thing happens in all themes.

**Comment by ZanderBrown** [comment]
This should move them all to the right (to be constant with other platforms)

Yes I'm aware of the blue, any attempt to remove it leads to the expander/branch icon disappearing (hence WIP of debug inspector)

**Comment by ntoll** [comment]
Aha... OK... we can fix the niggles later.

**Comment by ntoll** [comment]
Thanks for this work @ZanderBrown. See you tomorrow! ;-)

**Pull request merged**
