### PR TITLE
Add simplest possible help system.

### PR DESCRIPTION
**Pull request by ntoll**
This points to versioned documentation on the new http://codewith.mu/ website whose code is hosted here:

https://github.com/mu-editor/mu-editor.github.io

(Happy to add people as collaborators / admins to this project). ;-)

### CODE REVIEW

**Comment by carlosperate** [comment]
Updated the test to fix https://travis-ci.org/ntoll/mu/jobs/116461921#L388, should be all green now.

**Comment by carlosperate** [comment]
Anything blocking merging this into master?

**Comment by ntoll** [comment]
Some actual help at the endpoint. ;-) I'll try to get something done this weekend. Unfortunately, "real work" has been occupying me recently.

**Comment by carlosperate** [comment]
Looks like this branch/PR can be deleted/closed?

**Comment by whaleygeek** [comment]
Is this ready to merge, I would like to close down ticket #95 but I don't see built-in docs in Mu? Pressing the help button in Mu takes me to an external website, which I cannot access when offline (e.g. on a Raspberry Pi for example, which we never have connected to the internet in our school club, because there is no internet in that classroom).

**Comment by carlosperate** [comment]
This PR only adds a link to the online documentation, which has already been implemented and present in master.
For offline documentation we would need to update mostly the way that the Mu application is packed (so the scripts to the CI servers).

**Comment by carlosperate** [comment]
@ntoll is it safe to assume we can close this PR and delete the branch?

**Comment by ntoll** [comment]
Closed... thanks for the prod @carlosperate

**Pull request closed without merging**
