### PR TITLE
Increase serial timeout for RawREPL when listing files

### PR DESCRIPTION
**Pull request by WayneKeenan**
This is an untested and noddy suggestion for #985

### CODE REVIEW

**Comment by WayneKeenan** [comment]
I've tested this against a current master dev build and it "WorksForMe(tm)"

**Comment by dybber** [comment]
Hi @WayneKeenan, could we meet in between, e.g. at 5-6 seconds when listing files?

**Comment by WayneKeenan** [comment]
> Hi @WayneKeenan, could we meet in between, e.g. at 5-6 seconds when listing files?

Fixed timeouts are never really a fix, exponential back off delays with an upper retry count bound are.

**Comment by ntoll** [comment]
Just waiting for an extended period of time without any indication to the user that something's going, on is a UX "bad smell". I also wonder if the serial connection hasn't been made after 1 second then it'll never be made. Thoughts..?

**Comment by WayneKeenan** [comment]
> Just waiting for an extended period of time without any indication to the user that something's going, on is a UX "bad smell". I also wonder if the serial connection hasn't been made after 1 second then it'll never be made. Thoughts..?

There’s more detailed info as to why it’s successfully taking longer than 1 sec in #986,  tl;dr performing Wifi setup in boot.py on ESP32 blocks serial for a number of seconds.

**Comment by dybber** [comment]
Just added a comment over at #985 about how I'm dealing with wifi connectivity while teaching.

**Comment by WayneKeenan** [comment]
I'm going to close this PR as it has a wider ranging impact on the more typical use case, it's just too noddy.

It would be better for me to create a new PR that reads an optional timeout set in Mu's config, or otherwise default it to 1.

This would support cases where a users knows that their particular `boot.py` takes a while to start, for what ever reason.

**Pull request closed without merging**
