### PR TITLE
Support for multiple devices, and refactor of the device-interfacing code

### PR DESCRIPTION
**Pull request by dybber**
This pull-request relates to MicroPython-modes (ESP, micro:bit, CircuitPython), and how devices are detected and shown in the UI. In the beginning this was an attempt to fix issue #988, but in the process various refactorings was necessary and, I also ended up fixing another bug (#839) in the process.

The pull-request includes:
 - a refactor of USB/serial-interfacing code, to separate concerns all serial interaction is moved to the modes, away from the general UI-code, more specifically a REPLConnection class has been created to handle the interactions
 - support for multiple devices, with a drop-down where users can select between devices, when there are more than one device connected. The new UI element is shown below.
 - a fix for issue #839 
 - devices are now able to be recognized based on manufacturer string

The refactoring should make it easier to maintain the MicroPython-modes in the future, and through the new dropdown menu it should be easier to get a fix for issue #810 as well.

**I would like to get feedback on:**
 - how well this works with various devices and platforms (especially on Windows/Linux), I only have Mac. @the-stanely has made some tests on his Windows-machine, where it seems to work for his uses. (Thanks!)
 - the new UI for indicating device connectivity + device selection

**UI:**

In Python mode, no change:

In micro:bit mode, without any connected device:

In micro:bit mode, with a connected device:

With multiple devices connected:

### CODE REVIEW

**Comment by dybber** [comment]
Well, it's not really multiple devices, but you can now select beween devices manually. This would in theory allow users to open multiple Mu-instances and interact with two devices in each their separate Mu-instance.

**Comment by carlosperate** [comment]
> This would in theory allow users to open multiple Mu-instances and interact with two devices in each their separate Mu-instance.

I think right now Mu might assume in some places that is only a single instance running, things like sharing the settings file and log file, could be problematic if more than once instance was running at the same time.

For simplicity I would probably go the other way and force the editor being a "single instance" app (https://github.com/mu-editor/mu/issues/276), but that doesn't mean that we couldn't just track these issues and resolve them to support it.

**Comment by the-stanely** [comment]
I tested this version with 3 simultaneous ESP32s from 3 different manufacturers.  It worked great.  Startup opened the most recent session.  I didn't see any problems opening different files in different instances.  Admittedly, I rarely use the log.  When I do, something went wrong.  This has been rare.

I think the ability to open multiple instances with several devices is more powerful than the ability to keep the log straight -- though I don't know if the log gets confused in that case.

When developing multiple devices that communicate with each other, being able to debug them simultaneously is an excellent feature.  This is especially true with ESP32 which come with WiFi and Bluetooth.

**Comment by the-stanely** [comment]
Other features for Mu.  I realize that Mu is supposed to be targeted at beginners, but some advanced features would benefit everybody.  Adding an F3 key for 'search again' would be great.  This is a standard feature in many editors and would speed software development for users.

The search and search replace feature is cumbersome.  There is no edit menu, so users have to know in advance to use ^F.  This might be a mystery to new users, it doesn't affect me.

Occasionally I forget that I replaced something recently, then when I go to search new, I get a replace.  Would it make sense for the find/replace popup to have 'Find', 'Replace', and 'Replace All' buttons?

One of Mu's nice feature is that it integrates some of ampy with the 'Files' feature.  When upip is used, it creates sub-directories.  It would be nice if Mu's 'Files' capability was enhanced to navigate the file structure, especially on the left side.  Right side navigation enhancement would be great too.  Basically, navigating into sub-directories and parent directory '..' would be a valuable enhancement.

**Comment by dybber** [comment]
Hi @the-stanely: 
Great that this have worked for you. I hope this might find it's way into a next release of Mu.

I'm don't have any good solutions for the multiple instances issue right now. I think @carlosperate is right, that the best solution and what everyone else seems to do, is to make it a single-instance application, and then from there try to make support for having different tabs running with different modes, or having multiple windows within the same app. I still think the contribution in this issue simplifies a lot behind that scenes, that perhaps would make this easier to do at least for the micro:bit/ESP-mode/CircuitPython modes.

Regarding your last comment on this issue, please add such other suggestions as individual issues, then they will not be forgotten when this issue is closed. Posting them here also might clutter the discussion around this particular issue. Thanks!

**Comment by dybber** [comment]
Sorry, I shouldn't have merged, but rebased. I will see if I can redo this, and then try to do a force-push so we don't clutter the commit history too much!

**Comment by dybber** [comment]
I've rebased with master and the pull-request should be ready to merge.

**Comment by tjguk** [comment]
@dybber I'll leave others to comment technically as the devices aren't really my area, but from a quick perusal of the code changes I'd say it's a solid piece of work. I very much hope we can get it merged in without any difficulty.

**Comment by dybber** [comment]
Okay, thanks anyway for the nice comment :-) 

Btw. I forgot to mention earlier, that I also have some Inkscape svg's of the chip-connected chip-disconnected icons, which I didn't know where to put, so they are actually yet to be committed. Should they be committed to `mu/resources/images`, even though they aren't used in the UI?

**Comment by ZanderBrown** [comment]
If not the UI where are they used?

**Comment by dybber** [comment]
The PNG’s are used in the UI, was just questioning whether I should commit the vector versions as well (svg format)

**Comment by ZanderBrown** [comment]
Ah, with newer images I think we've just been using the SVG itself

**Comment by ntoll** [comment]
OK... I've tested this on Linux with:

* CircuitPython CPX and Bluetooth version thereof. :heavy_check_mark: 
* Microbit. :heavy_check_mark: 
* ESP8266/ESP32 :heavy_check_mark: 

All works for me. I'm going to merge this.

Thank you so much to @dybber for his outstanding work (and even more outstanding patience with me reviewing it). Here's to a quicker turn around next time. :wink:

**Comment by ntoll** [comment]
OK... hold on that merge. There's some linting and (micro:bit) unit test failures as the branch currently stands. Try it with:

```
$ make check
```

I'm just off to do some dad taxiing, but will try to fix the test fails tomorrow (then merge).

**Comment by ntoll** [comment]
Hurrah...! Fixed and merged. :rocket: :shipit:

**Pull request merged**
