### PR TITLE
Prevent creation of multiple venvs during testing

### PR DESCRIPTION
**Pull request by tjguk**
Sort out a problem creating venvs (clashing version of pyserial)
Plus ensure that no real venvs are created in Mu's standard data dir

### CODE REVIEW

**Comment by ntoll** [comment]
@tjguk this is stacked on my (un-merged and currently broken) splash screen branch. How about we merge into **that** (not `master`) and then when my branch lands, it's all fixed. Alternatively, perhaps re-submit just *your* changes stacked on master and I'll rebase my splash screen from master when we've landed this PR. I don't mind which. :-)

**Comment by tjguk** [comment]
Ok; let me see how readily I can reapply to master. If that's straightforward enough (and I think it will be) I'll merge into that. If it's more complicated I'll leave you to merge into your branch.

**Comment by carlosperate** [comment]
master is currently broken without the pyserial version relaxation, can we merge that first?

**Review by carlosperate — APPROVED** [review]
I've cherry picked the commits in a branch from master in https://github.com/mu-editor/mu/pull/1329 (there was only small conflicts on the tests, although it looks like maybe all the test changes were already present in master?), gave this a run works well.

Feel free to update this PR if you prefer, or merge the other one, but we have a couple of users unable to run from master so I thought it could speed this up a bit by running and testing from https://github.com/mu-editor/mu/pull/1329 .

**Comment by carlosperate** [comment]
Merged in https://github.com/mu-editor/mu/pull/1329.

**Pull request closed without merging**
