### PR TITLE
Make line number column width dynamic and follow zoom-levels

### PR DESCRIPTION
**Pull request by dybber**
Fix for #238

### CODE REVIEW

**Comment by ntoll** [comment]
I'll merge this. But the debugger (breakpoint, current line) related images in the column don't also change size. I remember this is controlled by QScintilla and I'm not even sure if it's possible.

**Comment by dybber** [comment]
> I'll merge this. But the debugger (breakpoint, current line) related images in the column don't also change size. I remember this is controlled by QScintilla and I'm not even sure if it's possible.

Do you want me to investigate that part as well? I think QScintilla is pretty customizable, so it should be doable

**Comment by ntoll** [comment]
Please do.... I agree that QScintilla is very customizable... except the documentation can be VERY confusing. My intuition isn't so much "could we do this..?" as "can we work out the simplest incantation in code to make this work?" ;-)

It may just be a couple of lines of Python or the mother-of-all hacks. If the latter, let's discuss.... if the former just do it..! :-)

**Comment by dybber** [comment]
So it was pretty easy, I just had to change the margins around the debugger-marker as well, and then the image resized as it had less space to fill. At least it works on Mac. See the new PR #1311

**Pull request merged**
