### PR TITLE
Specify our own close tab icon

### PR DESCRIPTION
**Pull request by ZanderBrown**
Partly for cross-platform consistency but also an attempt at a workaround for #397 

No idea if it'll work but if anyone has a mac it's worth a shot

Half the Qt documentation later I finally worked out how to reference images form resources, nothing like helpful docs :smile:

### CODE REVIEW

**Comment by ZanderBrown** [comment]
I can provide my source SVGs if that'll help but I'm no icon designer

[close.zip](https://github.com/mu-editor/mu/files/1884013/close.zip)

They are drawn at 24x24px but were exported at 16x16px

**Comment by ntoll** [comment]
In the end, after quite a bit of experimentation I've used the "cross" from font awesome (the same source as the icons for the buttons).

**Comment by ZanderBrown** [comment]
Seems a good choice then

**Comment by willingc** [comment]
Nice! Confirming that this works now :-) Thanks @ZanderBrown and @ntoll.

**Pull request merged**
